### ISSUE TITLE
Unsure what the cause is but i have up to date modlist

### ISSUE THREAD

**Issue by NicosaurusRex99** [McJty/RFTools#1056]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  SurgeLoadingPlugin (Surge-1.10.2-1.1.0.68.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.6r.jar)
  offlineskins (OfflineSkins-1.10.2-v2a.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  LucraftForgeLoading (LucraftCore-1.10.2-1.0.1.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 2/26/17 10:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DeepResonance (deepresonance)
Caused by: java.lang.RuntimeException: Error registering packets, this version of DeepResonance is probably incompatible with the installed version of ElecCore.
	at mcjty.deepresonance.network.DRMessages.registerNetworkMessages(DRMessages.java:24)
	at mcjty.deepresonance.proxy.CommonProxy.preInit(CommonProxy.java:41)
	at mcjty.deepresonance.proxy.ClientProxy.preInit(ClientProxy.java:24)
	at mcjty.deepresonance.DeepResonance.preInit(DeepResonance.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:387)
	at mcjty.deepresonance.network.DRMessages.registerNetworkMessages(DRMessages.java:18)
	... 39 more

**Comment by McJty** [comment]
Downgrade electors.  There are some issues

**Comment by NicosaurusRex99** [comment]
Alrighty

**Comment by McJty** [comment]
Electoren i mean

**Comment by NicosaurusRex99** [comment]
also swapping foamfix to law edition has fixed it. not your mod

**Comment by NicosaurusRex99** [comment]
so thats asie's fault?!?

**Comment by McJty** [comment]
Stupid autocorrect.  Eleccore

**Comment by NicosaurusRex99** [comment]
i knew what u meant LEL
