### ISSUE TITLE
RFTools crash

### ISSUE THREAD

**Issue by letruongthinh** [McJty/RFTools#1176]
---- Minecraft Crash Report ----
// Oops.

Time: 05:34 07/05/2017
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.block.Block.func_180643_i(net.minecraft.block.state.IBlockState)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:189)
	at mcjty.rftools.proxy.CommonProxy.reflect(CommonProxy.java:128)
	at mcjty.rftools.proxy.CommonProxy.preInit(CommonProxy.java:68)
	at mcjty.rftools.proxy.ClientProxy.preInit(ClientProxy.java:46)
	at mcjty.rftools.RFTools.preInit(RFTools.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:618)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:477)
	at net.minecraft.client.Minecraft.run(Minecraft.java:386)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
Caused by: java.lang.NoSuchMethodException: net.minecraft.block.Block.func_180643_i(net.minecraft.block.state.IBlockState)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:180)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 794168048 bytes (757 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.10.2-12.18.3.2281.jar) 
	UCH	Forge{12.18.3.2281} [Minecraft Forge] (forgeSrc-1.10.2-12.18.3.2281.jar) 
	UCH	multiplerelations{1.10.2-1.0.0} [name] (bin) 
	UCH	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCH	chickens{4.3.2} [Chickens] (chickens-4.3.2-deobf.jar) 
	UCE	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	Loaded coremods (and transformers):

**Comment by McJty** [comment]
NVidia card? If so update your driver

**Comment by McJty** [comment]
Also more info is always welcome (like what you were doing and such)

**Comment by McJty** [comment]
Also possibly your forge is too old

**Comment by letruongthinh** [comment]
I am using forge 1.10.2-12.18.3.2281. And I think there is no method called func_180643_i in net.minecraft.Block. I think there is actually a problem that the mod can't reflect func_180643_i to set something

**Comment by McJty** [comment]
That is Block.getSilkTouchDrop and that certainly exists in 1.10.2. And also it works for me on my 1.10.2 Lets Play just fine (and for many others using RFTools on 1.10.2). So something else is going on that prevents this from working. What other mods do you have?

**Comment by letruongthinh** [comment]
No there currently isn't. I am developing and I had searched for the field. Didn't have

**Comment by McJty** [comment]
Trust me it exists. Make sure you have recent mappings:

[15:33] -MCPBot_Reborn- === MC 1.10.2: net/minecraft/block/Block.getSilkTouchDrop (akf.u) UNLOCKED ===
[15:33] -MCPBot_Reborn- Name       : u => func_180643_i => getSilkTouchDrop
[15:33] -MCPBot_Reborn- Descriptor : (Lars;)Ladz; => (Lnet/minecraft/block/state/IBlockState;)Lnet/minecraft/item/ItemStack;
[15:33] -MCPBot_Reborn- AT         : public net.minecraft.block.Block func_180643_i(Lnet/minecraft/block/state/IBlockState;)Lnet/minecraft/item/ItemStack; # getSilkTouchDrop
[15:33] -MCPBot_Reborn- Comment    : None
[15:33] -MCPBot_Reborn- SRG Params : IBlockState p_180643_1_
[15:33] -MCPBot_Reborn- MCP Params : IBlockState state
[15:33] -MCPBot_Reborn- Last Change: 2016-11-15 13:02:03.233090-05:00 (bspkrs)

Also the mod *does* work on 1.10.2. It is heavily used (RFTools is one of the most active 1.10.2 mods right now)

Anyway, modlist please?

**Comment by letruongthinh** [comment]
That method now is called _createStackedBlock_. Your mcp might be old

**Comment by letruongthinh** [comment]
And also I have searched in the _methods.csv_

**Comment by letruongthinh** [comment]
And finally I have searched the method _getSilkTouchDrop_ in the _methods.csv_ but it didn't exist

**Comment by McJty** [comment]
Sorry but you seem to be ignoring me.

RFTOOLS WORKS FINE FOR EVERYONE ELSE ON 1.10.2.

And even if the mappings are outdated then the unmapped name still works.

Please give me the info I asked.

**Comment by letruongthinh** [comment]
I am using 1.10.2 version like everyone else. The mod list is:
Eligible Adapter ( I am currently developing)
Chickens

**Comment by McJty** [comment]
Ah is this in dev env perhaps? That's entirely different. You should have said that.

**Comment by McJty** [comment]
Anyway, your mod list isn't complete as McJtyLib and CompatLayer are required for rftools and you didn't mention those. So complete mod list with full versions please?

Also can you confirm you are talking about dev env? That changes things a lot

**Comment by letruongthinh** [comment]
Eligible Adapter 1.0.0 ( I am currently developing)
Chickens 4.3.2
McJtyLib 	1.1x-2.3.11
CompatLayer 1.10-0.2.8
RFTools 1.1x-6.00

**Comment by McJty** [comment]
And my question? Is this from a dev env? (inside a java IDE) or not?

**Comment by letruongthinh** [comment]
Yes, it is

**Comment by McJty** [comment]
Ok, and how are you using rftools in your dev env? Did you just put it in your run/mods folder or via build.gradle?

**Comment by letruongthinh** [comment]
In the run/mods folder. Because I have several machines in my mod that work using RF so I use your mod to generate RF

**Comment by McJty** [comment]
Hmm, you might have to change your mappings to use snapshot_20161117  to get this to work. That's the mapping that should have the correct getSilkTouchDrop

**Comment by letruongthinh** [comment]
It showed up with recomplied mc error: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':recompileMc'

**Comment by McJty** [comment]
Hmm no idea about that. Any other errors? Not really my thing though

**Comment by letruongthinh** [comment]
It is mcp snapshot error. Because not every snapshots work. I think that you are trying to use method that isn't existed or removed

**Comment by McJty** [comment]
The method is ok. But it seems I cannot convince you so I'm going to leave it at that. Sorry

**Comment by McJty** [comment]
BTW, one last comment. I use 'stable_29' for my 1.10.2 project which is the last stable and in that mapping it is already called Block.getSilkTouchDrop():

![image](https://cloud.githubusercontent.com/assets/8188472/25852520/edeaf75c-34c9-11e7-8907-109339816353.png)

**Comment by letruongthinh** [comment]
Might be I should download stable 29 instead of snapshot. Thanks anyway
