### ISSUE TITLE
Crash client.

### ISSUE THREAD

**Issue by Pilad** [McJty/RFTools#118]
Time: 23.03.15 16:18
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.mcjty.rftools.items.dimlets.KnownDimletConfiguration.setDimletKey(KnownDimletConfiguration.java:1052)
	at com.mcjty.rftools.crafting.KnownDimletShapedRecipe.func_77571_b(KnownDimletShapedRecipe.java:21)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:114)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:107)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.recipe.RecipeItemInputHandler.mouseClicked(RecipeItemInputHandler.java:36)
	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
	at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mcjty.rftools.items.dimlets.KnownDimletConfiguration.setDimletKey(KnownDimletConfiguration.java:1052)
	at com.mcjty.rftools.crafting.KnownDimletShapedRecipe.func_77571_b(KnownDimletShapedRecipe.java:21)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:114)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:107)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.recipe.RecipeItemInputHandler.mouseClicked(RecipeItemInputHandler.java:36)
	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
	at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: codechicken.nei.recipe.GuiUsageRecipe

**Comment by McJty** [comment]
I need a lot more information. How does this happen? Is this SMP? What version of RFTools?

**Comment by Pilad** [comment]
I use last ver. 2.70
I open NEI. And opened the recipe for gunpowder(mod Craftable Gunpowder.).
Link too mod: http://minecraft.curseforge.com/mc-mods/228602-craftable-gunpowder
And click in recipe on ingot sulfure.
And crash...

**Comment by McJty** [comment]
That looks like a bug in Craftable Gunpowder then as it seems to be doing strange things on crafting recipes.

**Comment by Monstrel** [comment]
That is incorrect.  This crash is replicable with the only these mods installed under Forge 1291

CodeChiceknCore 1.0.4.35
CoFH Core 3.0.0RC7-211
NEI 1.0.4.90
RFtools 2.70

These are all the current versions of these mods.  The crash occurs when attempting to look up the recipe for any item in NEI, vanilla or otherwise.  Load a new world in SSP, open NEI, click on stone, immediate client crash with the stack trace reported above.

**Comment by McJty** [comment]
Hmm.. I have slightly different versions of the above but I cannot reproduce it with that. I will investigate further.

**Comment by Monstrel** [comment]
I'm happy to do further isolation testing if you'd like me to try out anything in particular.

**Comment by McJty** [comment]
Can you test if the latest dev build fixes the crash:

https://drone.io/github.com/McJty/RFTools

Thanks!

**Comment by Monstrel** [comment]
I replaced 2.70 with 2.70-n203, and I'm afraid it still crashes in the same way.  Crash log follows:

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/23/15 12:39 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.mcjty.rftools.items.dimlets.KnownDimletConfiguration.setDimletKey(KnownDimletConfiguration.java:1053)
	at com.mcjty.rftools.crafting.KnownDimletShapedRecipe.func_77571_b(KnownDimletShapedRecipe.java:21)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:114)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:107)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mcjty.rftools.items.dimlets.KnownDimletConfiguration.setDimletKey(KnownDimletConfiguration.java:1053)
	at com.mcjty.rftools.crafting.KnownDimletShapedRecipe.func_77571_b(KnownDimletShapedRecipe.java:21)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:114)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:107)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Monstrel'/412, l='MpServer', x=119.50, y=71.62, z=258.50]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (120,64,256), Chunk: (at 8,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 194 game time, 194 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 136 total; [EntityZombie['Zombie'/59, l='MpServer', x=46.03, y=29.00, z=190.69], EntityCreeper['Creeper'/60, l='MpServer', x=47.50, y=17.00, z=208.50], EntityZombie['Zombie'/77, l='MpServer', x=48.63, y=31.00, z=191.41], EntityZombie['Zombie'/78, l='MpServer', x=55.50, y=45.00, z=194.50], EntityZombie['Zombie'/85, l='MpServer', x=60.50, y=75.00, z=198.50], EntitySkeleton['Skeleton'/86, l='MpServer', x=59.50, y=56.00, z=237.50], EntityZombie['Zombie'/87, l='MpServer', x=52.50, y=46.00, z=274.50], EntityZombie['Zombie'/612, l='MpServer', x=88.34, y=74.00, z=199.34], EntityZombie['Zombie'/106, l='MpServer', x=68.50, y=17.00, z=233.50], EntitySkeleton['Skeleton'/107, l='MpServer', x=67.50, y=17.00, z=234.50], EntitySkeleton['Skeleton'/108, l='MpServer', x=67.50, y=17.00, z=233.50], EntitySkeleton['Skeleton'/109, l='MpServer', x=65.00, y=42.00, z=276.75], EntitySkeleton['Skeleton'/110, l='MpServer', x=66.50, y=50.00, z=280.50], EntityEnderman['Enderman'/111, l='MpServer', x=74.90, y=45.00, z=322.50], EntityCreeper['Creeper'/626, l='MpServer', x=184.50, y=36.00, z=334.50], EntityCreeper['Creeper'/627, l='MpServer', x=183.50, y=36.00, z=332.50], EntityCreeper['Creeper'/123, l='MpServer', x=87.50, y=12.00, z=239.50], EntityBat['Bat'/124, l='MpServer', x=91.25, y=11.00, z=232.50], EntityBat['Bat'/125, l='MpServer', x=91.21, y=12.15, z=236.95], EntityChicken['Chicken'/126, l='MpServer', x=88.50, y=65.00, z=239.50], EntityChicken['Chicken'/127, l='MpServer', x=92.59, y=66.00, z=238.62], EntityChicken['Chicken'/128, l='MpServer', x=88.66, y=64.00, z=241.22], EntityChicken['Chicken'/129, l='MpServer', x=88.53, y=64.00, z=242.75], EntityZombie['Zombie'/130, l='MpServer', x=90.50, y=22.00, z=264.50], EntityFallingBlock['Falling Block'/1666, l='MpServer', x=95.50, y=68.49, z=184.50], EntityChicken['Chicken'/131, l='MpServer', x=84.63, y=64.00, z=260.47], EntityChicken['Chicken'/132, l='MpServer', x=89.50, y=64.00, z=259.50], EntityChicken['Chicken'/133, l='MpServer', x=89.50, y=64.00, z=261.50], EntityChicken['Chicken'/134, l='MpServer', x=90.50, y=64.00, z=260.50], EntityCreeper['Creeper'/135, l='MpServer', x=83.31, y=16.00, z=283.53], EntityCreeper['Creeper'/136, l='MpServer', x=84.13, y=16.00, z=283.34], EntitySkeleton['Skeleton'/137, l='MpServer', x=91.50, y=55.00, z=281.50], EntityCreeper['Creeper'/138, l='MpServer', x=89.83, y=55.00, z=287.30], EntityCreeper['Creeper'/139, l='MpServer', x=90.84, y=55.00, z=282.96], EntitySkeleton['Skeleton'/140, l='MpServer', x=89.21, y=40.00, z=297.20], EntityZombie['Zombie'/141, l='MpServer', x=88.50, y=40.00, z=298.50], EntityZombie['Zombie'/142, l='MpServer', x=92.05, y=42.00, z=299.55], EntityZombie['Zombie'/143, l='MpServer', x=93.34, y=59.00, z=293.34], EntityBat['Bat'/144, l='MpServer', x=78.52, y=62.04, z=294.64], EntityChicken['Chicken'/149, l='MpServer', x=101.65, y=64.00, z=222.97], EntityChicken['Chicken'/150, l='MpServer', x=102.84, y=68.00, z=229.66], EntityChicken['Chicken'/151, l='MpServer', x=100.76, y=66.47, z=226.73], EntityChicken['Chicken'/152, l='MpServer', x=101.50, y=67.00, z=225.50], EntityZombie['Zombie'/153, l='MpServer', x=100.50, y=15.00, z=268.50], EntityBat['Bat'/154, l='MpServer', x=107.60, y=42.13, z=263.88], EntitySpider['Spider'/155, l='MpServer', x=110.79, y=41.00, z=273.71], EntityZombie['Zombie'/671, l='MpServer', x=164.50, y=47.00, z=281.50], EntityItem['item.tile.sapling.jungle'/164, l='MpServer', x=117.88, y=64.13, z=246.59], EntitySkeleton['Skeleton'/1711, l='MpServer', x=111.50, y=41.00, z=301.50], EntitySquid['Squid'/191, l='MpServer', x=119.36, y=56.04, z=295.50], EntitySquid['Squid'/192, l='MpServer', x=117.83, y=55.66, z=304.87], EntitySquid['Squid'/193, l='MpServer', x=118.50, y=55.19, z=297.48], EntitySquid['Squid'/194, l='MpServer', x=120.64, y=56.00, z=297.69], EntityItem['item.tile.sapling.oak'/706, l='MpServer', x=129.41, y=85.13, z=226.63], EntitySquid['Squid'/195, l='MpServer', x=113.49, y=56.00, z=307.09], EntityFallingBlock['Falling Block'/1736, l='MpServer', x=156.50, y=50.49, z=286.50], EntitySkeleton['Skeleton'/201, l='MpServer', x=117.50, y=38.00, z=305.50], EntityFallingBlock['Falling Block'/1737, l='MpServer', x=156.50, y=50.49, z=287.50], EntitySkeleton['Skeleton'/202, l='MpServer', x=118.50, y=38.00, z=306.50], EntityFallingBlock['Falling Block'/1738, l='MpServer', x=157.50, y=50.49, z=284.50], EntitySquid['Squid'/203, l='MpServer', x=111.53, y=57.41, z=309.50], EntityFallingBlock['Falling Block'/1739, l='MpServer', x=157.50, y=50.49, z=285.50], EntityFallingBlock['Falling Block'/1740, l='MpServer', x=157.50, y=50.49, z=286.50], EntityFallingBlock['Falling Block'/1741, l='MpServer', x=157.50, y=50.49, z=287.50], EntityFallingBlock['Falling Block'/1742, l='MpServer', x=158.50, y=49.49, z=284.50], EntityFallingBlock['Falling Block'/1743, l='MpServer', x=158.50, y=49.49, z=285.50], EntityFallingBlock['Falling Block'/1744, l='MpServer', x=158.50, y=50.49, z=286.50], EntityFallingBlock['Falling Block'/1745, l='MpServer', x=158.50, y=50.49, z=287.50], EntityFallingBlock['Falling Block'/1746, l='MpServer', x=159.50, y=49.49, z=283.50], EntityFallingBlock['Falling Block'/1747, l='MpServer', x=159.50, y=49.49, z=284.50], EntityFallingBlock['Falling Block'/1748, l='MpServer', x=159.50, y=49.49, z=285.50], EntityFallingBlock['Falling Block'/1749, l='MpServer', x=159.50, y=50.49, z=286.50], EntityFallingBlock['Falling Block'/1750, l='MpServer', x=157.50, y=50.49, z=289.50], EntityFallingBlock['Falling Block'/1751, l='MpServer', x=158.50, y=50.49, z=289.50], EntityChicken['Chicken'/224, l='MpServer', x=125.50, y=63.00, z=336.50], EntityChicken['Chicken'/225, l='MpServer', x=126.50, y=63.00, z=337.50], EntityChicken['Chicken'/234, l='MpServer', x=137.53, y=62.31, z=206.16], EntityWitch['Witch'/747, l='MpServer', x=63.50, y=43.00, z=295.50], EntityChicken['Chicken'/235, l='MpServer', x=141.47, y=64.00, z=199.53], EntityChicken['Chicken'/236, l='MpServer', x=138.50, y=63.00, z=209.50], EntitySpider['Spider'/237, l='MpServer', x=130.28, y=22.00, z=282.00], EntityChicken['Chicken'/238, l='MpServer', x=128.50, y=63.00, z=338.50], EntityFallingBlock['Falling Block'/1774, l='MpServer', x=207.50, y=46.49, z=277.50], EntityFallingBlock['Falling Block'/1775, l='MpServer', x=207.50, y=45.49, z=278.50], EntityFallingBlock['Falling Block'/1776, l='MpServer', x=206.50, y=45.49, z=277.50], EntityFallingBlock['Falling Block'/1777, l='MpServer', x=206.50, y=45.49, z=278.50], EntityFallingBlock['Falling Block'/1778, l='MpServer', x=207.50, y=45.49, z=279.50], EntityCreeper['Creeper'/756, l='MpServer', x=40.50, y=48.00, z=284.50], EntityCreeper['Creeper'/246, l='MpServer', x=150.25, y=47.00, z=179.38], EntityFallingBlock['Falling Block'/1786, l='MpServer', x=246.50, y=9.72, z=234.50], EntityFallingBlock['Falling Block'/1787, l='MpServer', x=247.50, y=10.72, z=235.50], EntityFallingBlock['Falling Block'/1788, l='MpServer', x=246.50, y=9.72, z=237.50], EntityFallingBlock['Falling Block'/1789, l='MpServer', x=247.50, y=9.72, z=237.50], EntityFallingBlock['Falling Block'/1790, l='MpServer', x=247.50, y=10.72, z=236.50], EntityZombie['Zombie'/255, l='MpServer', x=165.50, y=47.00, z=283.50], EntityFallingBlock['Falling Block'/1791, l='MpServer', x=247.50, y=9.72, z=238.50], EntityCreeper['Creeper'/256, l='MpServer', x=164.50, y=47.00, z=280.50], EntityFallingBlock['Falling Block'/1792, l='MpServer', x=247.50, y=9.72, z=239.50], EntitySquid['Squid'/257, l='MpServer', x=171.01, y=60.00, z=274.48], EntityChicken['Chicken'/258, l='MpServer', x=171.50, y=63.00, z=297.50], EntityChicken['Chicken'/259, l='MpServer', x=172.50, y=63.00, z=297.50], EntityChicken['Chicken'/260, l='MpServer', x=171.50, y=63.00, z=296.50], EntityChicken['Chicken'/261, l='MpServer', x=176.61, y=62.40, z=302.14], EntityChicken['Chicken'/262, l='MpServer', x=172.81, y=63.00, z=302.50], EntityChicken['Chicken'/263, l='MpServer', x=172.88, y=63.00, z=303.84], EntityChicken['Chicken'/264, l='MpServer', x=171.16, y=62.10, z=303.38], EntityFallingBlock['Falling Block'/1800, l='MpServer', x=253.50, y=41.18, z=244.50], EntityFallingBlock['Falling Block'/1801, l='MpServer', x=252.50, y=41.18, z=244.50], EntityFallingBlock['Falling Block'/1802, l='MpServer', x=251.50, y=41.18, z=244.50], EntityFallingBlock['Falling Block'/1803, l='MpServer', x=250.50, y=41.18, z=244.50], EntityFallingBlock['Falling Block'/1804, l='MpServer', x=249.50, y=41.18, z=244.50], EntityFallingBlock['Falling Block'/1805, l='MpServer', x=248.50, y=41.18, z=244.50], EntityFallingBlock['Falling Block'/1806, l='MpServer', x=248.50, y=41.18, z=245.50], EntityCreeper['Creeper'/275, l='MpServer', x=188.22, y=37.00, z=231.45], EntitySkeleton['Skeleton'/787, l='MpServer', x=158.68, y=50.00, z=289.42], EntityCreeper['Creeper'/276, l='MpServer', x=182.50, y=25.00, z=253.50], EntityCreeper['Creeper'/788, l='MpServer', x=156.50, y=50.00, z=287.50], EntityChicken['Chicken'/277, l='MpServer', x=189.41, y=64.00, z=257.53], EntityCreeper['Creeper'/789, l='MpServer', x=158.49, y=50.00, z=288.48], EntityChicken['Chicken'/278, l='MpServer', x=186.75, y=65.00, z=253.44], EntityCreeper['Creeper'/790, l='MpServer', x=156.50, y=50.00, z=289.50], EntityChicken['Chicken'/279, l='MpServer', x=192.16, y=62.32, z=260.09], EntitySquid['Squid'/284, l='MpServer', x=179.50, y=61.00, z=268.50], EntitySquid['Squid'/285, l='MpServer', x=180.46, y=60.00, z=271.88], EntitySquid['Squid'/287, l='MpServer', x=179.22, y=60.38, z=276.91], EntitySquid['Squid'/288, l='MpServer', x=176.23, y=60.71, z=277.53], EntitySquid['Squid'/290, l='MpServer', x=177.93, y=60.23, z=275.72], EntitySkeleton['Skeleton'/299, l='MpServer', x=197.50, y=30.00, z=243.50], EntityZombie['Zombie'/813, l='MpServer', x=85.50, y=41.00, z=296.50], EntityBat['Bat'/307, l='MpServer', x=200.33, y=33.27, z=340.66], EntityBat['Bat'/308, l='MpServer', x=191.55, y=31.04, z=339.50], EntityBat['Bat'/846, l='MpServer', x=79.27, y=47.08, z=312.24], EntityCreeper['Creeper'/919, l='MpServer', x=73.50, y=46.00, z=270.50], EntityCreeper['Creeper'/932, l='MpServer', x=54.50, y=17.00, z=233.50], EntitySkeleton['Skeleton'/933, l='MpServer', x=66.50, y=17.00, z=227.50], EntityClientPlayerMP['Monstrel'/412, l='MpServer', x=119.50, y=71.62, z=258.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177116624 bytes (168 MB) / 370544640 bytes (353 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rftools{2.70} [RFTools] (rftools-2.70.n203.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore: -[1.7.10]3.0.0RC7-211
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.0.0 - Build 9.18.10.3324, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by McJty** [comment]
Ok, in a few seconds build 204 should be ready which hopefully fixes it for real now :-)
Doing blind fixing here...

**Comment by McJty** [comment]
Ok, 204 is ready

**Comment by Monstrel** [comment]
204 appears to fix the error.  Recipes are available in NEI as expected.  Nice job coding with a blindfold :-)

**Comment by McJty** [comment]
Thanks for testing this for me :-)
