### ISSUE TITLE
'client' crash due to FinderCompass (mod) incompatibility ? 

### ISSUE THREAD

**Issue by siccaxe** [McJty/RFTools#1204]
Upon entering any dimension, I get a crash to the server select screen regardless of whether the game is single player or multiplayer. Upon log inspection, I found the following error prior to the crash:

```
[01:14:50] [Netty Server IO #6/ERROR]: There was a critical exception handling a packet on channel AS_FC
java.lang.NoSuchMethodError: mcjty.lib.compat.CompatMapGenStructure.getClosestStrongholdPos(Lnet/minecraft/world/gen/structure/MapGenStructure;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/BlockPos;
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.clGetStrongholdGen(GenericChunkGenerator.java:596) ~[GenericChunkGenerator.class:?]
	at mcjty.lib.compat.CompatChunkGenerator.func_180513_a(CompatChunkGenerator.java:17) ~[CompatChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:304) ~[lr.class:?]
	at atomicstryker.findercompass.common.network.StrongholdPacket.readBytes(StrongholdPacket.java:81) ~[StrongholdPacket.class:?]
	at atomicstryker.findercompass.common.network.NetworkHelper$ChannelCodec.decodeInto(NetworkHelper.java:194) ~[NetworkHelper$ChannelCodec.class:?]
	at atomicstryker.findercompass.common.network.NetworkHelper$ChannelCodec.decodeInto(NetworkHelper.java:173) ~[NetworkHelper$ChannelCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103) ~[FMLIndexedMessageToMessageCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:4.0.23.Final]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:446) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:269) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:326) [LocalChannel.class:4.0.23.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:45) [LocalChannel.class:4.0.23.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:312) [LocalChannel$5.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

upon removing FinderCompass, errors and crashes stopped. I assume this is a problem with their code, but figured I'd mention it here as well. Full log if needed.

rftoolsdim-1.1x-4.55

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/110

**Comment by siccaxe** [comment]
Looks like my assumption was wrong (that's pretty common). FinderCompass' author recommended I try to locate a stronghold in the dimension with the vanilla method of 'using' an eye of ender. I couldn't, it did nothing when I attempted. I got a similar error in the log after the action:

```
[22:38:42] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: mcjty.lib.compat.CompatMapGenStructure.getClosestStrongholdPos(Lnet/minecraft/world/gen/structure/MapGenStructure;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/BlockPos;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoSuchMethodError: mcjty.lib.compat.CompatMapGenStructure.getClosestStrongholdPos(Lnet/minecraft/world/gen/structure/MapGenStructure;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/BlockPos;
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.clGetStrongholdGen(GenericChunkGenerator.java:596) ~[GenericChunkGenerator.class:?]
	at mcjty.lib.compat.CompatChunkGenerator.func_180513_a(CompatChunkGenerator.java:17) ~[CompatChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:304) ~[lr.class:?]
	at net.minecraft.item.ItemEnderEye.func_77659_a(SourceFile:80) ~[adk.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

```

There isn't a crash with this error, perhaps it just crashes when the action is carried out?

Is locating a stronghold with an eye of ender disabled in dimensions? 

Full log from original post (with FinderCompass)
[5-26.txt](https://github.com/McJty/RFTools/files/1033946/5-26.txt)

Full log from today (without FinderCompass)
[5-27.txt](https://github.com/McJty/RFTools/files/1033947/5-27.txt)

rftoolsdim-1.1x-4.55
rftools-1.1x-6.00
mcjtylib-1.1x-2.3.11
compatlayer-1.10-0.2.8

**Comment by McJty** [comment]
compatlayer-1.10-0.2.8

That's the problem. You're not using the latest version (0.2.9 fixes this)

**Comment by siccaxe** [comment]
lol! way to stay ahead of the game I suppose!

that's my luck, finding a bug 2 days ago that was patched 3 days prior.  I try to keep up with updates on your twitter. Thanks for the help!
