### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#122]
It happens if i goto title screen after been in a world and dimension hopping, and then going back into the world. 

[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]: Dimension information for dimension -127 is missing!
[10:40:58] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.setSeed(GenericWorldProvider.java:57) ~[GenericWorldProvider.class:?]
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.func_76555_c(GenericWorldProvider.java:169) ~[GenericWorldProvider.class:?]
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:245) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[10:40:58] [Server thread/ERROR]: This crash report has been saved to: D:\FTB\FTBInfinity\minecraft\crash-reports\crash-2015-03-24_10.40.58-server.txt
[10:40:58] [Server thread/INFO] [FML]: Applying holder lookups
[10:40:58] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[10:40:58] [Server thread/INFO] [FML]: Holder lookups applied
[10:40:58] [pool-5-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Trasciever data saved to D:\FTB\FTBInfinity\minecraft\saves\TS#5\enderio\dimensionalTransceiver.json
[10:40:58] [Server thread/INFO] [STDOUT]: [com.mcjty.rftools.RFTools:serverStopped:185]: ###### RFTools.serverStopped
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]: Cleaning up RFTools dimensions
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 129
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 128
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 130
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 46
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 47
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 45
[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 51

(blah blah blah) 

[10:40:58] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Already unregistered! Dimension: 127

**Comment by power-spike** [comment]
Time: 24/03/15 10:40 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.setSeed(GenericWorldProvider.java:57)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.func_76555_c(GenericWorldProvider.java:169)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654)
	at net.minecraft.world.World.<init>(World.java:245)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by power-spike** [comment]
Oh, FTB Infinity, Mekanism 8 (526), and RF Tools 2.64

**Comment by McJty** [comment]
Dimension -127? How many dimensions did you make? Be aware that you cannot currently make dimensions beyond id 128. It looks as if you went beyond that number.

**Comment by McJty** [comment]
This is a minecraft limitation btw. The logon packet only has space for a single byte of dimension information.

**Comment by power-spike** [comment]
that might explain the issues i am having, dimension 131 just went missing, and i'm upto dimension 132...

**Comment by McJty** [comment]
Since there isn't much I can do about this I'm closing it. BTW, you can use /rftdim safedel to reuse dimension you no longer need.
