### ISSUE TITLE
Ticking Tile Entity on power cell

### ISSUE THREAD

**Issue by TheHQBanana** [McJty/RFTools#1295]
I got this error and a crash after placing a petrified fuel generator from Industrial Foregoing against the powercell and fueling it.

-- Head --
Thread: Client thread
Stacktrace:
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.getNetwork(PowerCellTileEntity.java:156)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergyMulti(PowerCellTileEntity.java:481)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergyFacing(PowerCellTileEntity.java:470)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergy(PowerCellTileEntity.java:458)
	at p455w0rd.teslafied.tesla.RFHandler.givePower(RFHandler.java:42)
	at net.ndrei.teslacorelib.tileentities.ElectricGenerator$protectedUpdate$1.invoke(ElectricGenerator.kt:155)
	at net.ndrei.teslacorelib.tileentities.ElectricGenerator$protectedUpdate$1.invoke(ElectricGenerator.kt:27)
	at net.ndrei.teslacorelib.tileentities.ElectricGenerator.protectedUpdate(ElectricGenerator.kt:172)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:162)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:788)

-- Block entity being ticked --
Details:
	Name: industrialforegoing:petrified_fuel_generator_tile // com.buuz135.industrial.tile.generator.PetrifiedFuelGeneratorTile
	Block type: ID #2614 (tile.industrialforegoing.petrified_fuel_generator // com.buuz135.industrial.tile.block.PetrifiedFuelGeneratorBlock)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-1991,77,1992), Chunk: (at 9,4,8 in -125,124; contains blocks -2000,0,1984 to -1985,255,1999), Region: (-4,3; contains chunks -128,96 to -97,127, blocks -2048,0,1536 to -1537,255,2047)
	Actual block type: ID #2614 (tile.industrialforegoing.petrified_fuel_generator // com.buuz135.industrial.tile.block.PetrifiedFuelGeneratorBlock)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)

**Comment by McJty** [comment]
Versions please. But in any case, that looks like a bug in teslacore though

**Comment by McJty** [comment]
It could be that teslacorelib is trying to read RF on client side and that's not legal
