### ISSUE TITLE
Server Crash when everyone logs off

### ISSUE THREAD

**Issue by jpoblocki77** [McJty/RFTools#1315]
---- Minecraft Crash Report ----
// You're mean.

Time: 7/30/17 5:23 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraft.server.MinecraftServer.func_130014_f_(MinecraftServer.java:1496)
	at mcjty.rftools.dimension.DimensionTickEvent.serverTick(DimensionTickEvent.java:57)
	at mcjty.rftools.dimension.DimensionTickEvent.onServerTick(DimensionTickEvent.java:52)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_784_DimensionTickEvent_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

[17:23:02] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraft.server.MinecraftServer.func_130014_f_(MinecraftServer.java:1496) ~[MinecraftServer.class:?]
	at mcjty.rftools.dimension.DimensionTickEvent.serverTick(DimensionTickEvent.java:57) ~[DimensionTickEvent.class:?]
	at mcjty.rftools.dimension.DimensionTickEvent.onServerTick(DimensionTickEvent.java:52) ~[DimensionTickEvent.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_784_DimensionTickEvent_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251) ~[FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:23:02] [Server thread/ERROR]: This crash report has been saved to: C:\Minecraft\.\crash-reports\crash-2017-07-30_17.23.02-server.txt
[17:23:02] [Server thread/INFO]: Stopping server

FTB infinity evolved preferred kcauldron newest version 1614. if I stay logged into the server I am fine but once everyone logs off the server for the night 10 mins later I get these errors and the server crashes.

**Comment by McJty** [comment]
I am on vacation right now.  Will look at this when I am back

**Comment by jpoblocki77** [comment]
about how long will that be as my minecraft server is completely unplayable and im tired of liting to my plays say they want it up

**Comment by McJty** [comment]
7 days from now.  Note that I no longer work on the 1.7.10 version of rftools but maybe you can tell me when this started happening?

Also why is this a serious problem? Can't you auto restart the server when it crashes?

**Comment by jpoblocki77** [comment]
It started as soon as i started the server.  The server cannot be auto restarted I have to login and manually reset it everytime.  I am not willing to log in every 5-10 mins just to keep the server running I do need sleep too ya know.

I have tried all the variuous fixes i find online for very similar problems but none of them have worked.

**Comment by McJty** [comment]
I mean, when did this problem first start? Was there an update or something? Nobody has ever reported something like this before

**Comment by jpoblocki77** [comment]
As soon as I started the server the first time

**Comment by McJty** [comment]
Ah so it has never worked. In that case I recommend removing kcauldron. That plugin has been known to cause problems with some mods

**Comment by jpoblocki77** [comment]
I have tried that with a brand new world and ghot the same result.  I cannot get rid of kcauldron because i would have no way of running the plugins i use,  and yes i have already tested it with out the plugins and get the same result

**Comment by jpoblocki77** [comment]
brand new world without cauldron and got the same result is what I meant

**Comment by jpoblocki77** [comment]
so what should i use to run all my plugins if cauldron is so bad

**Comment by jpoblocki77** [comment]
[17:25:17] [Server thread/INFO]: Loading scripts
[17:25:17] [Server thread/INFO]: MineTweaker: Loading InfinityPackWideChanges.zs
[17:25:17] [Server thread/INFO]: World ID: f4ad1d85-4bff-4bce-a8df-f1e94bfc443f
[17:25:17] [Server thread/INFO]: [4.0.0-beta-6] World config does not exist, generating.
[17:25:17] [Server thread/INFO]: RFTools: server is starting
[17:25:17] [Server thread/INFO]: Registering RFTools dimensions
[17:25:19] [KCauldron version retrievier/INFO]: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://api.prok.pw:443: The target server failed to respond
[17:25:19] [KCauldron version retrievier/INFO]: Retrying request to {s}->https://api.prok.pw:443
[17:25:20] [KCauldron version retrievier/INFO]: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://api.prok.pw:443: The target server failed to respond
[17:25:20] [KCauldron version retrievier/INFO]: Retrying request to {s}->https://api.prok.pw:443
[17:25:21] [KCauldron version retrievier/INFO]: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://api.prok.pw:443: The target server failed to respond
[17:25:21] [KCauldron version retrievier/INFO]: Retrying request to {s}->https://api.prok.pw:443
[17:25:21] [KCauldron version retrievier/WARN]: Error occured during retriving version
java.lang.Throwable
	at kcauldron.KLog.log(KLog.java:30) [KLog.class:1.7.10-R0.1-SNAPSHOT]
	at kcauldron.KLog.warning(KLog.java:41) [KLog.class:1.7.10-R0.1-SNAPSHOT]
	at kcauldron.updater.KVersionRetriever.uncaughtException(KVersionRetriever.java:114) [KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
	at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:108) [KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
	at kcauldron.updater.KVersionRetriever.run(KVersionRetriever.java:69) [KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: org.apache.http.NoHttpResponseException: api.prok.pw:443 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[DefaultHttpResponseParser.class:4.4.1]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[DefaultHttpResponseParser.class:4.4.1]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[AbstractMessageParser.class:4.4.1]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[DefaultBHttpClientConnection.class:4.4.1]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[CPoolProxy.class:4.4.1]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[HttpRequestExecutor.class:4.4.1]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[HttpRequestExecutor.class:4.4.1]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[MainClientExec.class:4.4.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[ProtocolExec.class:4.4.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[RetryExec.class:4.4.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[RedirectExec.class:4.4.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[InternalHttpClient.class:4.4.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[CloseableHttpClient.class:4.4.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[CloseableHttpClient.class:4.4.1]
	at kcauldron.updater.KVersionRetriever.check(KVersionRetriever.java:92) ~[KVersionRetriever.class:1.7.10-R0.1-SNAPSHOT]
	... 2 more

**Comment by McJty** [comment]
I think you should report this to cauldron. There is nothing that I can do on my side
