### ISSUE TITLE
Load existing world crush

### ISSUE THREAD

**Issue by sPECIIKOMODO** [McJty/RFTools#133]
java.lang.IllegalArgumentException: Failed to register dimension for id 34, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.registerDimensionToServerAndClient(RfToolsDimensionManager.java:174)
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.registerDimensions(RfToolsDimensionManager.java:168)
	at com.mcjty.rftools.dimension.ModDimensions.initDimensions(ModDimensions.java:18)
	at com.mcjty.rftools.RFTools.serverStarted(RFTools.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:752)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by McJty** [comment]
More information please? What version of RFTools? Single player/server? When does this happen?

**Comment by McJty** [comment]
Ah I recognize that problem. That is in infinity right? There was a bug in one version of infinity with another dimension mod that accidentally registered this dimension. Update infinity. It should be fixed now.

**Comment by McJty** [comment]
The problem in infinity was with Runic Dungeons. It has a problem specifically with dimension 34. Perhaps you should look at that if you have that in your modpack?

**Comment by sPECIIKOMODO** [comment]
Yes that was the problem tnx!!!
