### ISSUE TITLE
Rftools 1.12 Dimensions "Disappearing"

### ISSUE THREAD

**Issue by ossuman** [McJty/RFTools#1339]
In my single player creative testworld I have a dimension that will seemingly disappear. If I log off inside of it upon relogging I'm placed at spawn as if I had a broken bed. Once stepping on the transmitter to enter the missing dimension it says the dimension is invalid (I'm not sure of the exact message as after my last backup restore it's not happening). When I restored from the most recent backup I was able to log onto the world one time with the dimension working fine, then after logging out and back in the same problem occurs. I went back a few backups and it seems to be working for now. Finally, after the second relog where the dimension is missing on the third one the entire world fails to load and minecraft appears to stop responding. I left it for about 30 minutes at one point to see if it would either crash itself or eventually load and it did not. This is happening in the All The Mods 3 modpack. If there's any useful information I left out that could help. A lot of it is fairly ambiguous but although the problem is perfectly repeatable I haven't been able to pinpoint any single problem.

UPDATE: After it happened again in my older backup I checked the logs right away so I didn't have to comb through a bunch of other stuff and this is the error it seems to throw (Dimension 13 is the breaking dimension)

`[19:00:47] [Server thread/ERROR]: Cannot Hotload Dim: 13
java.lang.IllegalArgumentException: Could not get provider type for dimension 13, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:146) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:233) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:826) [MinecraftServer.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:117) [pj.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:258) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:74) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:207) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [ox.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chb.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[19:00:47] [Server thread/ERROR]: Cannot Hotload Dim: 13
java.lang.IllegalArgumentException: Could not get provider type for dimension 13, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:146) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:233) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:826) [MinecraftServer.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:119) [pj.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:258) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:74) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:207) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [ox.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chb.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]`

**Comment by McJty** [comment]
I need to see the entire server log. Preferably the one where the dimension was created. Also how did you create that dimension? What dimlets?
