### ISSUE TITLE
Fatal Error and server disconnect

### ISSUE THREAD

**Issue by psychofad** [McJty/RFTools#137]
I just upgraded to RFTools 2.73 to make use of the ability to read the Draconic Evolution energy core and whenever I go near enough to my energy core for the chunks to render on my client I am getting disconnected with a fatal error.  I looked through my client logs and there was no info there at all, but when I look on my server logs I see the error below repeatedly (I did try to reconnect quite a few times).  

using:
RFTools 2.73
Draconic-Evolution-1.7.10-v1.0.1-RC-4

```
[19:40:42] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NoClassDefFoundError: brandon3055/draconicevolution/api/IExtendedRFStorage
	at mcjty.rftools.apideps.DraconicEvolutionCompatibility.isPowerStorage(DraconicEvolutionCompatibility.java:8) ~[DraconicEvolutionCompatibility.class:?]
	at mcjty.varia.EnergyTools.getEnergyLevelMulti(EnergyTools.java:62) ~[EnergyTools.class:?]
	at mcjty.rftools.blocks.screens.modules.EnergyBarScreenModule.getData(EnergyBarScreenModule.java:31) ~[EnergyBarScreenModule.class:?]
	at mcjty.rftools.blocks.screens.ScreenTileEntity.getScreenData(ScreenTileEntity.java:355) ~[ScreenTileEntity.class:?]
	at mcjty.rftools.blocks.screens.network.PacketGetScreenData.onMessage(PacketGetScreenData.java:54) ~[PacketGetScreenData.class:?]
	at mcjty.rftools.blocks.screens.network.PacketGetScreenData.onMessage(PacketGetScreenData.java:13) ~[PacketGetScreenData.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: brandon3055.draconicevolution.api.IExtendedRFStorage
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 28 more
Caused by: java.lang.NullPointerException
```

**Comment by psychofad** [comment]
Reverting to RFTools 2.72 allows me to once again visit my energy core.  I did open up the Draconic Evolution RC-4 jar file in WinRar just to check if the api was still in there and it is indeed.  The only thing that looked any different was that the path to it was `com/brandon3055/draconicevolution/api/IExtendedRFStorage.class` but as I am no coder I really don't know if the com is necessary or not.  For now i will just continue to use 2.72 as it is still working.  Let me know if I can do any tests for you as I never update my client/server directly.  I have a test client/server that I update first just in case of these kinds of situations.

**Comment by McJty** [comment]
Ah apparently I used the wrong package. I'll fix that. Also you can go back to 2.73 if you temporarily remove the energy module that refers to the Draconic Ore core.

**Comment by McJty** [comment]
Can you check again with the latest dev snapshot: https://drone.io/github.com/McJty/RFTools/files

That should fix the api

**Comment by psychofad** [comment]
Well..that fixed it.  At first I was gonna say that I still can't read the power in it, because if you shift right click on the energy core it will still just clear the module, but if you shift right click the module on an energy pylon that is either inputting or outputting to the core it will read the energy in the core.  Might want to document that on your site(s) so as to clear up any confusion on how to utilize the DE compatibility, but I think you have a working build here!  Thanks!

**Comment by psychofad** [comment]
![Screen](http://i.imgur.com/c9PqvgU.png)

**Comment by McJty** [comment]
Oh nice :-) Thanks for testing this! I'll close this now since it is fixed.
