### ISSUE TITLE
NPE: Crash during server startup

### ISSUE THREAD

**Issue by Boreeas** [McJty/RFTools#140]
Happens with both v2.73 and v2.74

```
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at CoroUtil.forge.CoroAI.writeOutData(CoroAI.java:103)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at CoroUtil.forge.CoroAI.serverStop(CoroAI.java:84)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.Loader.serverStopped(Loader.java:800)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:483)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489)
[18:47:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[18:47:08] [Server thread/WARN] [EnderIO]: Failed to write Transciever Channels on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[18:47:08] [Server thread/ERROR] [morphadditions]: Skipping event FMLServerStoppedEvent and marking errored mod morphadditions since required dependency Morph has errored
[18:47:08] [Server thread/INFO] [STDOUT]: [mcjty.rftools.RFTools:serverStopped:192]: ###### RFTools.serverStopped
[18:47:08] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:47:08] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
```

**Comment by Boreeas** [comment]
Ack, the RFTools line made me think it's an RFTool error. On closer inspection, it's obviously not.
