### ISSUE TITLE
crashes when trying to take remote storage scanner from inventory

### ISSUE THREAD

**Issue by mabelrxu** [McJty/RFTools#1464]
I have a storage scanner scanning 2 of those storage blocks with storage modules inside them, and a remote access module linked to the scanner. When I use the storage scanner or the remote access module to try to remove the "remote storage scanner" item I have inside the system, it crashes.

error message:
`[11:58:34] [Netty Local Client IO #0/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:524) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [DefaultEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[11:58:34] [Netty Local Client IO #0/INFO]: [AstralSorcery] Cleaning client cache...
[11:58:34] [Netty Local Client IO #0/INFO]: [AstralSorcery] Cleared cached client data! Disconnected from server.`

can't tell what the problem is, it doesn't seem to crash with other items ... please let me know if you need me to try any other steps.

**Comment by mabelrxu** [comment]
on DIreWolf20 1.12 pack

**Comment by McJty** [comment]
hmm yes. This is hard to solve but those items simply contain too many items and so the network packet becomes too big

**Comment by josephcsible** [comment]
I wonder if overriding getNBTShareTag would be beneficial here.
