### ISSUE TITLE
Crash with redstone reciver and transmitter

### ISSUE THREAD

**Issue by newcatxtreme** [McJty/RFTools#1494]
Hi firts time posting something here, just starting to play with rftools and crash my world when i set the redstone transmitter and reciver and send a redstone signal

Crash report: 
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b130.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 12/19/17 11:46 AM
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at mcjty.rftools.blocks.builder.BuilderTileEntity.restartScan(BuilderTileEntity.java:2062)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.setPowerInput(BuilderTileEntity.java:605)
	at mcjty.lib.container.GenericBlock.checkRedstone(GenericBlock.java:528)
	at mcjty.lib.container.GenericBlock.func_189540_a(GenericBlock.java:278)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at net.minecraft.world.World.func_175685_c(World.java:492)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:158)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:340)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at mcjty.rftools.blocks.logic.generic.LogicTileEntity.setRedstoneState(LogicTileEntity.java:39)
	at mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity.checkStateServer(RedstoneReceiverTileEntity.java:31)
	at mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity.func_73660_a(RedstoneReceiverTileEntity.java:26)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.rftools.blocks.builder.BuilderTileEntity.restartScan(BuilderTileEntity.java:2062)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.setPowerInput(BuilderTileEntity.java:605)
	at mcjty.lib.container.GenericBlock.checkRedstone(GenericBlock.java:528)
	at mcjty.lib.container.GenericBlock.func_189540_a(GenericBlock.java:278)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)

-- Block being updated --
Details:
	Source block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block: rftools:builder[facing=west]
	Block location: World: (-1731,63,807), Chunk: (at 13,3,7 in -109,50; contains blocks -1744,0,800 to -1729,255,815), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at net.minecraft.world.World.func_175685_c(World.java:492)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:158)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:340)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)

-- Block being updated --
Details:
	Source block type: ID #2551 (tile.rftools.redstone_receiver_block // mcjty.rftools.blocks.logic.wireless.RedstoneReceiverBlock)
	Block: minecraft:redstone_wire[east=none,north=none,power=0,south=none,west=none]
	Block location: World: (-1732,63,806), Chunk: (at 12,3,6 in -109,50; contains blocks -1744,0,800 to -1729,255,815), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at mcjty.rftools.blocks.logic.generic.LogicTileEntity.setRedstoneState(LogicTileEntity.java:39)
	at mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity.checkStateServer(RedstoneReceiverTileEntity.java:31)
	at mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity.func_73660_a(RedstoneReceiverTileEntity.java:26)

-- Block entity being ticked --
Details:
	Name: minecraft:rftools_redstone_receiver_block // mcjty.rftools.blocks.logic.wireless.RedstoneReceiverTileEntity
	Block type: ID #2551 (tile.rftools.redstone_receiver_block // mcjty.rftools.blocks.logic.wireless.RedstoneReceiverBlock)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-1732,63,807), Chunk: (at 12,3,7 in -109,50; contains blocks -1744,0,800 to -1729,255,815), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
	Actual block type: ID #2551 (tile.rftools.redstone_receiver_block // mcjty.rftools.blocks.logic.wireless.RedstoneReceiverBlock)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: BCCWorld
	All players: 1 total; [EntityPlayerMP['Pramo'/453, l='BCCWorld', x=-1731.92, y=63.00, z=813.65]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: 5072473303048387263
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1682304528 bytes (1604 MB) / 4103901184 bytes (3913 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2564 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                  | Source                                              | Signature                                |
	|:--------- |:----------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                   | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                     | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.1.2564.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.1.2564             | forge-1.12.2-14.23.1.2564.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | actuallyadditions       | 1.12.2-r126              | ActuallyAdditions-1.12.2-r126.jar                   | None                                     |
	| UCHIJAAAA | appliedenergistics2     | rv5-stable-3             | appliedenergistics2-rv5-stable-3.jar                | None                                     |
	| UCHIJAAAA | bdlib                   | 1.14.3.10                | bdlib-1.14.3.10-mc1.12.2.jar                        | None                                     |
	| UCHIJAAAA | ae2stuff                | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | jei                     | 4.8.5.138                | jei_1.12.2-4.8.5.138.jar                            | None                                     |
	| UCHIJAAAA | appleskin               | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
	| UCHIJAAAA | aroma1997core           | 2.0.0.0.b130             | Aroma1997Core-1.12.2-2.0.0.0.b130.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aroma1997sdimension     | 2.0.0.2.b61              | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b61.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | astralsorcery           | 1.8.4                    | astralsorcery-1.12.2-1.8.4.jar                      | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAA | quark                   | r1.4-120                 | Quark-r1.4-120.jar                                  | None                                     |
	| UCHIJAAAA | autoreglib              | 1.3-15                   | AutoRegLib-1.3-15.jar                               | None                                     |
	| UCHIJAAAA | baubles                 | 1.5.1                    | Baubles-1.12-1.5.1.jar                              | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                            | None                                     |
	| UCHIJAAAA | ctm                     | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                              | None                                     |
	| UCHIJAAAA | chisel                  | MC1.12-0.1.1.24          | Chisel-MC1.12-0.1.1.24.jar                          | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12-2.8.1.49            | TConstruct-1.12-2.8.1.49.jar                        | None                                     |
	| UCHIJAAAA | bhc                     | 1.1.0b                   | baubley-heart-canisters-1.12.2-1.1.0b.jar           | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCHIJAAAA | bookshelf               | 2.3.512                  | Bookshelf-1.12.2-2.3.512.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | botania                 | r1.10-352                | Botania r1.10-352.jar                               | None                                     |
	| UCHIJAAAA | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| UCHIJAAAA | chesttransporter        | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                     | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux            | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar             | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore                | 4.3.7                    | CoFHCore-1.12.2-4.3.7.25-universal.jar              | None                                     |
	| UCHIJAAAA | cofhworld               | 1.0.2                    | CoFHWorld-1.12.2-1.0.2.10-universal.jar             | None                                     |
	| UCHIJAAAA | cucumber                | 1.0.3                    | cucumber-1.12-1.0.3.jar                             | None                                     |
	| UCHIJAAAA | cyclopscore             | 0.10.24                  | CyclopsCore-1.12.2-0.10.24.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | waila                   | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                           | None                                     |
	| UCHIJAAAA | p455w0rdslib            | 2.0.24                   | p455w0rdslib-1.12-2.0.24.jar                        | None                                     |
	| UCHIJAAAA | danknull                | 1.2.19                   | DankNull-1.12-1.2.19.jar                            | None                                     |
	| UCHIJAAAA | darkutils               | 1.8.188                  | DarkUtils-1.12.2-1.8.188.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | forestry                | 5.7.0.218                | forestry_1.12.2-5.7.0.218.jar                       | None                                     |
	| UCHIJAAAA | eleccore                | 1.8.434                  | ElecCore-1.12.2-1.8.434.jar                         | None                                     |
	| UCHIJAAAA | deepresonance           | 1.5.0                    | deepresonance-1.12-1.5.0.jar                        | None                                     |
	| UCHIJAAAA | elevatorid              | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                        | None                                     |
	| UCHIJAAAA | embers                  | 0.230                    | embers-0.230.jar                                    | None                                     |
	| UCHIJAAAA | enderstorage            | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | valkyrielib             | 1.12.2-2.0.6a            | valkyrielib-1.12.2-2.0.6a.jar                       | None                                     |
	| UCHIJAAAA | environmentaltech       | 1.12.2-2.0.6a            | environmentaltech-1.12.2-2.0.6a.jar                 | None                                     |
	| UCHIJAAAA | everlastingabilities    | 1.3.9                    | EverlastingAbilities-1.12.2-1.3.9.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | immersiveengineering    | 0.12-75                  | ImmersiveEngineering-0.12-75.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | mekanism                | 1.12.2-9.4.3.330         | Mekanism-1.12.2-9.4.3.330.jar                       | None                                     |
	| UCHIJAAAA | thermalfoundation       | 2.3.7                    | ThermalFoundation-1.12.2-2.3.7.18-universal.jar     | None                                     |
	| UCHIJAAAA | thermalexpansion        | 5.3.7                    | ThermalExpansion-1.12.2-5.3.7.31-universal.jar      | None                                     |
	| UCHIJAAAA | exchangers              | 1.12-2.5.2               | Exchangers-1.12-2.5.2.jar                           | None                                     |
	| UCHIJAAAA | extracells              | 2.5.9                    | ExtraCells-1.12.2-2.5.9a45.jar                      | None                                     |
	| UCHIJAAAA | extrautils2             | 1.0                      | extrautils2-1.12-1.7.1.jar                          | None                                     |
	| UCHIJAAAA | zerocore                | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                           | None                                     |
	| UCHIJAAAA | bigreactors             | 1.12-0.4.5.44            | ExtremeReactors-1.12-0.4.5.44.jar                   | None                                     |
	| UCHIJAAAA | fastleafdecay           | v14                      | FastLeafDecay-v14.jar                               | None                                     |
	| UCHIJAAAA | sonarcore               | 5.0.3                    | sonarcore-1.12.2-5.0.3.jar                          | None                                     |
	| UCHIJAAAA | fluxnetworks            | 3.0.1                    | fluxnetworks-1.12.2-3.0.1.jar                       | None                                     |
	| UCHIJAAAA | forgelin                | 1.6.0                    | Forgelin-1.6.0.jar                                  | None                                     |
	| UCHIJAAAA | gendustry               | 1.6.5.6                  | gendustry-1.6.5.6-mc1.12.2.jar                      | None                                     |
	| UCHIJAAAA | guideapi                | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                         | None                                     |
	| UCHIJAAAA | teslacorelib            | 1.0.12                   | tesla-core-lib-1.12-1.0.12.jar                      | None                                     |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.6.3-107.jar            | None                                     |
	| UCHIJAAAA | instantunify            | 1.1.0                    | instantunify-1.12.2-1.1.0.jar                       | None                                     |
	| UCHIJAAAA | mysticalagriculture     | 1.6.7                    | mysticalagriculture-1.12-1.6.7.jar                  | None                                     |
	| UCHIJAAAA | harvestcraft            | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                      | None                                     |
	| UCHIJAAAA | rftools                 | 7.15                     | rftools-1.12-7.15.jar                               | None                                     |
	| UCHIJAAAA | integrationforegoing    | 1.12-1.4                 | IntegrationForegoing-1.12-1.4.jar                   | f8b632eee30601ba63fe0984fae017fc7800f2fe |
	| UCHIJAAAA | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks           | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar                    | None                                     |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                     | None                                     |
	| UCHIJAAAA | jeibees                 | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                        | None                                     |
	| UCHIJAAAA | journeymap              | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                         | None                                     |
	| UCHIJAAAA | jeresources             | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar             | None                                     |
	| UCHIJAAAA | llor                    | 1.1.4-mc1.12             | LLOverlayReloaded-1.1.4-mc1.12.jar                  | None                                     |
	| UCHIJAAAA | mekanismgenerators      | 9.4.3                    | MekanismGenerators-1.12.2-9.4.3.330.jar             | None                                     |
	| UCHIJAAAA | mekanismtools           | 9.4.3                    | MekanismTools-1.12.2-9.4.3.330.jar                  | None                                     |
	| UCHIJAAAA | mob_grinding_utils      | 0.3.4                    | MobGrindingUtils-0.3.4.jar                          | None                                     |
	| UCHIJAAAA | mousetweaks             | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                        | None                                     |
	| UCHIJAAAA | rangedpumps             | 0.5                      | rangedpumps-0.5.jar                                 | None                                     |
	| UCHIJAAAA | redstonearsenal         | 2.3.7                    | RedstoneArsenal-1.12.2-2.3.7.18-universal.jar       | None                                     |
	| UCHIJAAAA | rftoolscontrol          | 1.7.0                    | rftoolsctrl-1.12-1.7.0.jar                          | None                                     |
	| UCHIJAAAA | rftoolsdim              | 5.05                     | rftoolsdim-1.12-5.05.jar                            | None                                     |
	| UCHIJAAAA | roguelike               | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                  | None                                     |
	| UCHIJAAAA | simplyenchanting        | 1.0.3                    | SimplyEnchanting-1.12-1.0.3.jar                     | None                                     |
	| UCHIJAAAA | storagedrawers          | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                     | None                                     |
	| UCHIJAAAA | thermaldynamics         | 2.3.7                    | ThermalDynamics-1.12.2-2.3.7.14-universal.jar       | None                                     |
	| UCHIJAAAA | twilightforest          | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar         | None                                     |
	| UCHIJAAAA | veinminer               | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar               | None                                     |
	| UCHIJAAAA | veinminermodsupport     | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar               | None                                     |
	| UCHIJAAAA | wailaharvestability     | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar               | None                                     |
	| UCHIJAAAA | wanionlib               | 1.12.2-1.4               | WanionLib-1.12.2-1.4.jar                            | None                                     |
	| UCHIJAAAA | wct                     | 3.8.55                   | WirelessCraftingTerminal-1.12.2-3.8.55.jar          | None                                     |
	| UCHIJAAAA | woot                    | 1.12.2-0.0.4             | woot-1.12.2-0.0.4.jar                               | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.12                   | tesla-core-lib-1.12-1.0.12.jar                      | None                                     |
	| UCHIJAAAA | unidict                 | 1.12.2-1.8               | UniDict-1.12.2-1.8.jar                              | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b130.jar)
  
ForgelinPlugin (Forgelin-1.6.0.jar)
  
AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r126.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-3.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.1.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12-0.4.5.44.jar
		* BotaniaAPI (88) from Botania r1.10-352.jar
		* chesttransporter|api (2) from ChestTransporter-1.12-2.8.7.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12-0.1.1.24.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.1.1.24.jar
		* cofhapi (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.12-1.5.0.jar
		* ElecCoreAPI (1.0) from ElecCore-1.12.2-1.8.434.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.12.2-1.8.434.jar
		* fluxapi (1.0) from fluxnetworks-1.12.2-3.0.1.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.7.0.218.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.7.0.218.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.6-mc1.12.2.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.4-57.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-75.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-75.jar
		* industrialforegoingapi (3) from industrialforegoing-1.12.2-1.6.3-107.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.138.jar
		* mcjtylib_ng (2.5.0) from mcjtylib-1.12-2.5.0.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.24.jar
		* QuarkAPI (1) from Quark-r1.4-120.jar
		* sonarapi (1.0.1) from sonarcore-1.12.2-5.0.3.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* valkyrielib.api (1.12-2.0.1a) from valkyrielib-1.12.2-2.0.6a.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.1.639+134fb1e.jar
		* WailaAPI (1.3) from Hwyla-1.8.23-B38_1.12.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.8.55.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Pramo'/453, l='BCCWorld', x=-1731.92, y=63.00, z=813.65]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by McJty** [comment]
Hmm weird. It actually crashes in the builder. I will check it out
