### ISSUE TITLE
RFtools crashing launcher

### ISSUE THREAD

**Issue by Nazdravanix** [McJty/RFTools#1538]
Trying to launch Direwolf20 pack (ver 1.4) and get a Java Binary has stopped crash when I hit the "Initialising Mods Phase 2" stage on RFTools

Set up a game using only RFTools mods and got the same crash.

Crash report here, 

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/1/18 5:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: java.lang.NoSuchMethodError: mcjty.lib.McJtyRegister.registerLater(Lnet/minecraft/block/Block;Lmcjty/lib/base/ModBase;Ljava/lang/Class;Ljava/lang/Class;)V
	at mcjty.rftools.blocks.MachineFrame.<init>(MachineFrame.java:22)
	at mcjty.rftools.blocks.ModBlocks.initBaseBlocks(ModBlocks.java:95)
	at mcjty.rftools.blocks.ModBlocks.init(ModBlocks.java:35)
	at mcjty.rftools.proxy.CommonProxy.preInit(CommonProxy.java:130)
	at mcjty.rftools.proxy.ClientProxy.preInit(ClientProxy.java:51)
	at mcjty.rftools.RFTools.preInit(RFTools.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 392184256 bytes (374 MB) / 950534144 bytes (906 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2582 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                        | Signature                                |
	|:----- |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML            | 8.0.99.99    | forge-1.12.2-14.23.1.2582.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge          | 14.23.1.2582 | forge-1.12.2-14.23.1.2582.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCE   | rftools        | 7.15         | rftools-1.12-7.15.jar         | None                                     |
	| UCE   | rftoolscontrol | 1.6.8        | rftoolsctrl-1.12-1.6.8.jar    | None                                     |
	| UCE   | rftoolsdim     | 5.05         | rftoolsdim-1.12-5.05.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.71' Renderer: 'GeForce GTX 1070/PCIe/SSE2'`

**Comment by josephcsible** [comment]
You're using mismatching versions of McJtyLib and RFTools.

**Comment by Nazdravanix** [comment]
Bah, have updated to the correct versions but am still getting the Java Binary Stopped error launcher is not producing a crash log anymore for some reason.

Game output log here https://pastebin.com/7xfTq07Y

**Comment by josephcsible** [comment]
Any update on this? There's no errors in what you last posted; without a crash log, there's nothing we can do.

**Comment by Nazdravanix** [comment]
Managed to sought it out on the end. Something wasn't right with Java on my system. Clean Java install didn't fix it, so in the end I gave up and reinstalled the OS and a fresh version of Java. After that everything worked. Not sure why it didn't like RFTools or what the actual issue with Java was  but it works now.
