### ISSUE TITLE
Server Crash now getting this message in the error log when it restarts

### ISSUE THREAD

**Issue by Exanadu** [McJty/RFTools#1591]
[14:39:23] [Server thread/INFO]: Starting minecraft server version 1.12.2
[14:40:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools Dimensions (rftoolsdim)

Caused by: java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[JsonElement.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:146) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:134) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRules(DimletRules.java:89) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.proxy.CommonProxy.preInit(CommonProxy.java:47) ~[CommonProxy.class:?]
	at mcjty.rftoolsdim.proxy.ServerProxy.preInit(ServerProxy.java:12) ~[ServerProxy.class:?]
	at mcjty.rftoolsdim.RFToolsDim.preInit(RFToolsDim.java:91) ~[RFToolsDim.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606) ~[ftbserver.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[ftbserver.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[ftbserver.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[14:40:33] [Server thread/ERROR]: This crash report has been saved to: /games/ni832873_1/ftproot/minecraftftb/./crash-reports/crash-2018-01-28_14.40.33-server.txt
[14:40:33] [Server thread/INFO]: Stopping server
[14:40:33] [Server thread/INFO]: Saving worlds
[14:40:33] [Server Shutdown Thread/INFO]: Stopping server
[14:40:33] [Server Shutdown Thread/INFO]: Saving worlds

**Comment by josephcsible** [comment]
You made a mistake editing your dimlets.json file. Pastebin the whole thing.

**Comment by Exanadu** [comment]
Well after you mentioned corruption I looked into the logs and noticed that the server ran out of allowed storage space because of the FTB backups every hour causing the server to crash and preventing the .json file from saving the data properly.

**Comment by Exanadu** [comment]
I will delete the backups and replace my config folder from a backup and see if we get somewhere

**Comment by Exanadu** [comment]
Deleting the backups and restoring the config folder fixed the problem. Thank you for pointing me in the right direction.
