### ISSUE TITLE
Unknown issue within Void Dimension

### ISSUE THREAD

**Issue by PiggyWhiskey** [McJty/RFTools#1615]
DW20 1.8.0
RFTools 7.2.4
RFToolsDim 5.51
RFToolsCTRL 1.8.0
Forge 14.23.1.2601

I created 2 dimensions, first was a void with debuffs, so recreated with some digits for a new void.
The Dimension worked perfectly fine, but I've started getting client crashes within 5 minutes of playing.

Dropbox with all logs: https://www.dropbox.com/sh/tmi95j45oy8cl06/AABeysqm_4ILpWGmJAdvd3kCa?dl=0

I honestly don't know what's causing it.
I thought it was a Refined Storage issue as it crashed when I was transferring items between disks.
However RS Dev said it was an RFTools Issue.

Noting that it doesn't crash all the time, and there isn't an issue/error on the server when the Dimension isn't populated.

Edit; I should mention, the void Dimension has 3 levels of 3x3 chunks that contains all my base/machine/automation.
I'm not sure how to cut those chunks to the overworld for testing either.

**Comment by josephcsible** [comment]
Is this the crash you're talking about?
```
[09:49:04] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at com.raoulvdberge.refinedstorage.item.ItemNetworkItem.getX(ItemNetworkItem.java:102) ~[ItemNetworkItem.class:?]
	at com.raoulvdberge.refinedstorage.tile.grid.WirelessGrid.<init>(WirelessGrid.java:63) ~[WirelessGrid.class:?]
	at com.raoulvdberge.refinedstorageaddons.item.WirelessCraftingGrid.<init>(WirelessCraftingGrid.java:36) ~[WirelessCraftingGrid.class:?]
	at com.raoulvdberge.refinedstorageaddons.apiimpl.network.grid.wireless.WirelessGridFactoryWirelessCraftingGrid.create(WirelessGridFactoryWirelessCraftingGrid.java:15) ~[WirelessGridFactoryWirelessCraftingGrid.class:?]
	at com.raoulvdberge.refinedstorage.gui.GuiHandler.getGrid(GuiHandler.java:161) ~[GuiHandler.class:?]
	at com.raoulvdberge.refinedstorage.gui.GuiHandler.getGridGui(GuiHandler.java:165) ~[GuiHandler.class:?]
	at com.raoulvdberge.refinedstorage.gui.GuiHandler.getClientGuiElement(GuiHandler.java:108) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:279) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
```
Also, can you link to where the RS Dev said it was an RFTools Dimensions issue?

**Comment by PiggyWhiskey** [comment]
RS issue: https://github.com/raoulvdberge/refinedstorage/issues/1645

The issue spamming the server while I'm logged in:

```
java.util.concurrent.ExecutionException:

 java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556) ~[amu.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:491) ~[amu.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:439) ~[amu.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380) ~[amu.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:925) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by josephcsible** [comment]
This bit of the stack trace makes me think that it's some coremod breaking something, not RS or RFTools Dimensions:
```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556) ~[amu.class:?]
```
Can you try disabling your coremods to see if that's it?

**Comment by PiggyWhiskey** [comment]
My coremods folders are totally empty.

**Comment by josephcsible** [comment]
The coremods folder is a historical artifact. Coremods are just in the regular mods folder now. All of these mods are coremods:
* Aroma1997Core-1.12.2-2.0.0.0.b139.jar
* Forgelin-1.6.0.jar
* ImmersiveEngineering-0.12-76-core.jar
* OpenComputers-MC1.12.1-1.7.1.43.jar
* ResourceLoader-MC1.12.1-1.5.3.jar
* astralsorcery-1.12.2-1.8.5.jar
* elulib-0.1.11.jar
* CTM-MC1.12-0.2.3.12.jar

**Comment by PiggyWhiskey** [comment]
With dependencies I disabled:

- blockcraftery-0.1.3.jar
- CTM-MC1.12-0.2.3.12.jar
- elulib-0.1.11.jar
- Forgelin-1.6.0.jar
- ImmersiveEngineering-0.12-76-core.jar
- industrialforegoing-1.12.2-1.7.0-114.jar
- ResourceLoader-MC1.12.1-1.5.3.jar
- tesla-core-lib-1.12-1.0.12.jar


It appeared stable. After 3 minutes

```
[10:58:06] [Server thread/INFO]: PiggyWhiskey joined the game
[11:01:26] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556) ~[amu.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:493) ~[amu.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:439) ~[amu.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380) ~[amu.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:360) ~[amu.class:?]
	at mcjty.xnet.blocks.cables.ConnectorBlock.removedByPlayer(ConnectorBlock.java:129) ~[ConnectorBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:324) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[11:01:26] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4437ms behind, skipping 88 tick(s)
[11:01:29] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556) ~[amu.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:493) ~[amu.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:439) ~[amu.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380) ~[amu.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:925) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by PiggyWhiskey** [comment]
Followed by:

```
[11:04:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556) ~[amu.class:?]
	at mcjty.xnet.blocks.cables.ConnectorTileEntity.setPowerOut(ConnectorTileEntity.java:81) ~[ConnectorTileEntity.class:?]
	at mcjty.xnet.apiimpl.logic.LogicChannelSettings.tick(LogicChannelSettings.java:127) ~[LogicChannelSettings.class:?]
	at mcjty.xnet.blocks.controller.TileEntityController.func_73660_a(TileEntityController.java:187) ~[TileEntityController.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[11:04:29] [Server thread/ERROR]: This crash report has been saved to: G:\Minecraft Server\Direwolf20 [1.8.0]\.\crash-reports\crash-2018-02-05_11.04.29-server.txt
[11:04:29] [Server thread/INFO]: Stopping server
[11:04:29] [Server thread/INFO]: Saving players
[11:04:29] [Server thread/INFO]: Saving worlds
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/Deep Dark
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/lostcities
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/twilight_forest
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/CompactMachines
[11:04:29] [Server thread/INFO]: Saving chunks for level 'world'/rftools_dimension
[11:04:30] [Server thread/INFO]: Saving chunks for level 'world'/Storage Cell
[11:04:31] [Server Shutdown Thread/INFO]: Stopping server
[11:04:31] [Server Shutdown Thread/INFO]: Saving players
```

So it may be an XNet issue then?

**Comment by josephcsible** [comment]
Is your Minecraft.jar file or Forge installation possibly corrupt? A NoClassDefFoundError of a vanilla class usually indicates this, if it's not a coremod at fault.

**Comment by PiggyWhiskey** [comment]
I re-downloaded a fresh .jar for both, with the same issue.
And then created a Single Player world to build the same setup.
Using just RFTools and XNet, had the same error.

Then narrowed it down further. It's an XNet issue.

If two Redstone Proxy (Update) are next to each other, that error comes up.
Within about 10-15 seconds of placing the second block.

I'll create an Issue in the XNet repo.
Feel free to close this one.

**Comment by PiggyWhiskey** [comment]
https://github.com/McJty/XNet/issues/230
