### ISSUE TITLE
[1.12.2] Crash

### ISSUE THREAD

**Issue by jefferyrlc** [McJty/RFTools#1736]
Issue description: 

Game suddenly crashed, at first I thought it had to do with the Ae2 inscriber I was working with, but upon review of the logs there's an error with rftools shield, which I haven't built in this world ever.

Steps to reproduce: I don't know how this occured

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2655
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.7
* RFTools: 1.12-7.33

Possibly incompatible mods and versions: 
using Optifine and FoamFix

Relevant logs, if any: 
https://paste.ee/p/hmDTM

**Comment by josephcsible** [comment]
The JourneyMap stuff is a red herring. It often spews a bunch of exceptions after a crash that it had nothing to do with. Here's the actual crash's stack trace:
```
java.lang.ClassCastException: de.ellpeck.actuallyadditions.mod.tile.TileEntityGiantChestLarge cannot be cast to mcjty.rftools.blocks.shield.NoTickShieldBlockTileEntity
	at mcjty.rftools.blocks.shield.AbstractShieldBlock.func_185477_a(AbstractShieldBlock.java:93)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1335)
	at net.minecraft.world.World.func_184143_b(World.java:1423)
	at net.minecraft.entity.Entity.func_145771_j(Entity.java:2376)
	at net.minecraft.entity.item.EntityXPOrb.func_70071_h_(EntityXPOrb.java:100)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

Your saved game appears to have gotten corrupt somehow: a block was marked as being a shield projector, but its tile entity was marked as being a giant chest from Actually Additions.
