### ISSUE TITLE
[Crash] Material None + Oregen = null pointer exception.

### ISSUE THREAD

**Issue by Lodran** [McJty/RFTools#185]
If you create a dimension table with Material None before Feature Oregen (in an attempt to get normal Ore Generation), a single player world will crash with a null pointer exception, while servers will disconnect players whenever they perform an action which causes the server to access the dimension table's description.

Caused by: java.lang.NullPointerException
        at mcjty.rftools.dimension.DimensionInformation.toBytes(DimensionInformation.java:64￼ ~[DimensionInformation.class:?]
        at mcjty.rftools.dimension.network.PacketSyncDimensionInfo.toBytes(PacketSyncDimensionInfo.java:70) ~[PacketSyncDimensionInfo.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageC

After rebooting, the dimension table's description reads "Error: dimension information missing", or something similar.

The exact set of dimlets I used to produce this was:

Material None
Feature Oregen
Liquid None
Material None
Terrain Islands

By removing the first "Material None", I was able to craft the world without crashing.

**Comment by McJty** [comment]
I'll fix this but putting material none before feature oregen will not give you normal ore generation. Normal ore generation is done by default.

**Comment by McJty** [comment]
Ah actually in RFTools 2.90 this is already fixed.
