### ISSUE TITLE
Serverside crash with shaper (Divide by zero)

### ISSUE THREAD

**Issue by DBotThePony** [McJty/RFTools#1899]
Unsafe division: https://github.com/McJtyMods/RFTools/blob/1.12/src/main/java/mcjty/rftools/blocks/shaper/ScannerTileEntity.java#L254
```
java.lang.ArithmeticException: / by zero
    at mcjty.rftools.blocks.shaper.ScannerTileEntity.writeRestorableToNBT(ScannerTileEntity.java:254)
    at mcjty.lib.tileentity.GenericTileEntity.writeToNBT(GenericTileEntity.java:299)
    at mcjty.lib.tileentity.GenericEnergyStorageTileEntity.writeToNBT(GenericEnergyStorageTileEntity.java:66)
    at mcjty.lib.tileentity.GenericTileEntity.writeClientDataToNBT(GenericTileEntity.java:212)
    at mcjty.lib.tileentity.GenericTileEntity.getUpdatePacket(GenericTileEntity.java:171)
    at net.minecraft.server.management.PlayerChunkMapEntry.sendBlockEntity(PlayerChunkMapEntry.java:288)
    at net.minecraft.server.management.PlayerChunkMapEntry.update(PlayerChunkMapEntry.java:250)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:115)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by McJty** [comment]
I need more information. Version numbers, what were you doing, ...

**Comment by DBotThePony** [comment]
RFTools: 1.12.2 7.60
Lib: 3.1.1
Forge: Build 2796

Crash can be reproduced by putting down a scanner and putting shape card with X width of 0 inside it and starting a scan

**Comment by McJty** [comment]
Should be fixed next release
