### ISSUE TITLE
(server-side) disableShieldBlocksToUncorruptWorld throws a NullPointerException

### ISSUE THREAD

**Issue by utf-4096** [McJty/RFTools#1972]
Issue description: (server-side) disableShieldBlocksToUncorruptWorld throws a NullPointerException

Steps to reproduce: 
 Enable disableShieldBlocksToUncorruptWorld in server config and restart the server.

Versions:
* Minecraft: 1.7.10
* Forge: 1614
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.8.1-SNAPSHOT
* RFTools: 4.23

Possibly incompatible mods and versions: 

Relevant logs, if any: 
```
[13:46:38] [Server thread/ERROR]: The following problems were captured during this phase
[13:46:38] [Server thread/ERROR]: Caught exception from rftools
java.lang.NullPointerException
        at net.minecraft.item.crafting.CraftingManager.func_92103_a(CraftingManager.java:256) ~[afe.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:278) ~[GameRegistry.class:1.7.10-1614.57]
        at cpw.mods.fml.common.registry.GameRegistry.addRecipe(GameRegistry.java:273) ~[GameRegistry.class:1.7.10-1614.57]
        at mcjty.rftools.blocks.blockprotector.BlockProtectorSetup.setupCrafting(BlockProtectorSetup.java:22) ~[BlockProtectorSetup.class:?]
        at mcjty.rftools.crafting.ModCrafting.init(ModCrafting.java:61) ~[ModCrafting.class:?]
        at mcjty.rftools.CommonProxy.preInit(CommonProxy.java:61) ~[CommonProxy.class:?]
        at mcjty.rftools.ServerProxy.preInit(ServerProxy.java:11) ~[ServerProxy.class:?]
        at mcjty.rftools.RFTools.preInit(RFTools.java:153) ~[RFTools.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at ...
[13:46:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
        at net.minecraft.item.crafting.CraftingManager.func_92103_a(CraftingManager.java:256) ~[afe.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:278) ~[GameRegistry.class:1.7.10-1614.57]
        at cpw.mods.fml.common.registry.GameRegistry.addRecipe(GameRegistry.java:273) ~[GameRegistry.class:1.7.10-1614.57]
        at mcjty.rftools.blocks.blockprotector.BlockProtectorSetup.setupCrafting(BlockProtectorSetup.java:22) ~[BlockProtectorSetup.class:?]
        at mcjty.rftools.crafting.ModCrafting.init(ModCrafting.java:61) ~[ModCrafting.class:?]
        at mcjty.rftools.CommonProxy.preInit(CommonProxy.java:61) ~[CommonProxy.class:?]
        at mcjty.rftools.ServerProxy.preInit(ServerProxy.java:11) ~[ServerProxy.class:?]
        at mcjty.rftools.RFTools.preInit(RFTools.java:153) ~[RFTools.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
...
```

**Comment by McJty** [comment]
Remove the custom recipe for crafting manager for the (now disabled) shield blocks

**Comment by utf-4096** [comment]
problem being, i did not set a custom recipe

**Comment by McJty** [comment]
Well there must be one because it is crashing in CraftTweaker

**Comment by utf-4096** [comment]
i couldnt find anything in the server files mentionning CraftingManager/CraftTweaker

**Comment by josephcsible** [comment]
@McJty it doesn't look like CraftTweaker to me either

**Comment by McJty** [comment]
Ah sorry. Looked wrong

**Comment by utf-4096** [comment]
any update on this issue?

**Comment by speedyplane2247** [comment]
Yeah, if you could fix this issue that'd be great. Also check edits!

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
