### ISSUE TITLE
1.14 Rendering Overlay crash

### ISSUE THREAD

**Issue by erwin1234777** [McJty/RFTools#1997]
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/12/19 4:03 PM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at mcjty.rftoolspower.setup.ClientRegistration.lambda$onModelBake$0(ClientRegistration.java:70) ~[?:1.14-1.2.9-alpha] {re:classloading}
	at mcjty.rftoolspower.setup.ClientRegistration$$Lambda$3115/1709586930.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at mcjty.rftoolspower.setup.ClientRegistration.onModelBake(ClientRegistration.java:69) ~[?:1.14-1.2.9-alpha] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_167_ClientRegistration_onModelBake_ModelBakeEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:28.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2844/647226268.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:363) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:58) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:17) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$2970/2120486917.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3098/1017279808.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.87.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/1687586610.call(Unknown Source) [forge-1.14.4-28.1.87.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcjty.rftoolspower.setup.ClientRegistration.lambda$onModelBake$0(ClientRegistration.java:70)
	at mcjty.rftoolspower.setup.ClientRegistration$$Lambda$3115/1709586930.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at mcjty.rftoolspower.setup.ClientRegistration.onModelBake(ClientRegistration.java:69)
	at net.minecraftforge.eventbus.ASMEventHandler_167_ClientRegistration_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at net.minecraftforge.fml.ModLoader$$Lambda$2844/647226268.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:363)
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:58)
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:17)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at net.minecraft.client.resources.ReloadListener$$Lambda$2970/2120486917.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$3098/1017279808.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/1687586610.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1290738760 bytes (1230 MB) / 2817523712 bytes (2687 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx11520m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.87.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.87.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.87.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.87.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.87.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.87
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.14.4-1.5.5.jar Cyclops Core {cyclopscore@1.5.5 CREATE_REGISTRIES}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 CREATE_REGISTRIES}
		Cucumber-1.14.4-2.0.5.jar Cucumber Library {cucumber@2.0.5 CREATE_REGISTRIES}
		jei-1.14.4-6.0.0.25.jar Just Enough Items {jei@6.0.0.25 CREATE_REGISTRIES}
		EverlastingAbilities-1.14.4-1.5.5.jar EverlastingAbilities {everlastingabilities@1.5.5 CREATE_REGISTRIES}
		caelus-FORGE-1.14.4-1.0.1.jar Caelus API {caelus@FORGE-1.14.4-1.0.1 CREATE_REGISTRIES}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 CREATE_REGISTRIES}
		Neat 1.5-19.jar Neat {neat@1.5-19 CREATE_REGISTRIES}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 CREATE_REGISTRIES}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 CREATE_REGISTRIES}
		rangedpumps-0.6.1.jar Ranged Pumps {rangedpumps@0.6.1 CREATE_REGISTRIES}
		ChanceCubes-1.14.4-4.0.0.298.jar Chance Cubes {chancecubes@1.14.4-4.0.0.298 CREATE_REGISTRIES}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b CREATE_REGISTRIES}
		mcjtylib-1.14-3.5.12-alpha.jar McJtyLib {mcjtylib@1.14-3.5.12-alpha CREATE_REGISTRIES}
		rftoolsbase-1.14-0.0.9-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.9-alpha CREATE_REGISTRIES}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version CREATE_REGISTRIES}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 CREATE_REGISTRIES}
		PackingTape-1.14.4-0.9.0.jar Packing Tape {packingtape@0.9.0 CREATE_REGISTRIES}
		JustEnoughResources-1.14.4-0.10.0.66.jar Just Enough Resources {jeresources@0.10.0.66 CREATE_REGISTRIES}
		rftoolspower-1.14-1.2.9-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.9-alpha CREATE_REGISTRIES}
		forge-1.14.4-28.1.87-universal.jar Forge {forge@28.1.87 CREATE_REGISTRIES}
		refinedstorage-1.7.jar Refined Storage {refinedstorage@1.7 CREATE_REGISTRIES}
		ColossalChests-1.14.4-1.7.4.jar ColossalChests {colossalchests@1.7.4 CREATE_REGISTRIES}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 CREATE_REGISTRIES}
		forge-1.14.4-28.1.87-client.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
		rftoolsutility-1.14-1.2.9-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.9-alpha CREATE_REGISTRIES}
		torchmaster-2.0.0-rc1.jar Torchmaster {torchmaster@2.0.0-rc1 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.14.4-1.3.8.jar EnchantmentDescriptions {enchdesc@1.3.8 CREATE_REGISTRIES}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 CREATE_REGISTRIES}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.257-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.256 CREATE_REGISTRIES}
		rftoolsbuilder-1.14-1.2.8-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.8-alpha CREATE_REGISTRIES}
		recall-1.14.4-1.2.jar Recall {recall@1.2 CREATE_REGISTRIES}
		randomenchants-2.1.0.jar Random Enchants {randomenchants@2.1.0 ERROR}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 CREATE_REGISTRIES}
		Quark-r2.0-199.jar Quark {quark@r2.0-199 CREATE_REGISTRIES}
		rftoolsstorage-1.14-0.0.4-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.4-alpha CREATE_REGISTRIES}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 CREATE_REGISTRIES}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 CREATE_REGISTRIES}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 CREATE_REGISTRIES}
		OreExcavation-1.6.141.jar Ore Excavation {oreexcavation@1.6.141 CREATE_REGISTRIES}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version CREATE_REGISTRIES}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 CREATE_REGISTRIES}
		tombstone-4.1.7-1.14.4.jar Corail Tombstone {tombstone@4.1.7 CREATE_REGISTRIES}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 CREATE_REGISTRIES}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 CREATE_REGISTRIES}
		solcarrot-1.14.4-1.9.3.jar Spice of Life: Carrot Edition {solcarrot@1.14.4-1.9.3 CREATE_REGISTRIES}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 CREATE_REGISTRIES}
		QuantumStorage-1.14.4-5.0.2.jar QuantumStorage {quantumstorage@NONE CREATE_REGISTRIES}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 CREATE_REGISTRIES}
		xptome-1.14.4-v1.1.4.jar XP Tome {xpbook@v1.1.4 CREATE_REGISTRIES}
	Launched Version: forge-28.1.87
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce 920M/PCIe/SSE2 GL version 4.6.0 NVIDIA 425.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

**Comment by McJty** [comment]
Known bug and most likely a bug in forge. Just start again

**Comment by erwin1234777** [comment]
Okey thank you
