### ISSUE TITLE
 Dimlet.json does not load correctly in the game

### ISSUE THREAD

**Issue by dani6102** [McJty/RFTools#2142]
Issue description: 
Basically I tried to install RFtools and RFtoolsdimensions in a private modpack, when I searched for dimlets in the JEI only a couple of them were displayed, checking the files the dimlet.json appears and the dimlets are shown in it but for some reason they are not loaded in the game.
later i tried to create a profile with a few mods inside to test if it worked or not, and it didn't work.
I also tried to download a modpack (FTB Presents direwolf20 1.12 version 2.8.0) but even in that case the dimlets are not shown, also I tried to create a dimension without dimlet, but it does not allow me to teleport inside it as it does not detect a matter reciever

Steps to reproduce: 
I don't know if it is caused by conflicts between the mods but with these mods the dimlets are not shown:
just download the mods and search for dimlets,

codechicken lib 1.8+
CoFH core
CoFH world
Journeymap
Jei
McJtyLib
Redstone FLux
RFtools
RFtoolsDimensions
Thermal Dynamics
Thermal Expansion
Thermal Foundation

Versions:
* Minecraft:  1.12.2
* Forge: 14.23.5.2855
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:

Possibly incompatible mods and versions: 

Relevant logs, if any: 
This is the last log i have, i'm not sure if it contains something usefull or not.
(it's not a crash)

[11:34:06] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:34:06] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[11:34:06] [main/INFO]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[11:34:06] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\utente\Documents\Curse\Minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
[11:34:07] [main/INFO]: Searching C:\Users\utente\Documents\Curse\Minecraft\Instances\test RFTOOL\mods for mods
[11:34:07] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:34:07] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:34:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:34:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:34:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:34:10] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[11:34:10] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[11:34:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:34:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:34:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[11:34:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[11:34:11] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[11:34:16] [Client thread/INFO]: Setting user: dani6102
[11:34:22] [Client thread/WARN]: Skipping bad option: lastServer:
[11:34:22] [Client thread/INFO]: LWJGL Version: 2.9.4
[11:34:24] [Client thread/INFO]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 578033288 bytes (551 MB) / 740818944 bytes (706 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
[11:34:24] [Client thread/INFO]: MinecraftForge v14.23.5.2855 Initialized
[11:34:24] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[11:34:24] [Client thread/INFO]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[11:34:24] [Client thread/INFO]: Replaced 1227 ore ingredients
[11:34:25] [Client thread/INFO]: Searching C:\Users\utente\Documents\Curse\Minecraft\Instances\test RFTOOL\mods for mods
[11:34:27] [Client thread/WARN]: Mod codechickenlib is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.2.3.358
[11:34:28] [Thread-3/INFO]: Using alternative sync timing : 200 frames of Display.update took 1145447300 nanos
[11:34:29] [Client thread/INFO]: Forge Mod Loader has identified 16 mods to load
[11:34:30] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, codechickenlib, cofhcore, cofhworld, jei, journeymap, mcjtylib_ng, redstoneflux, rftools, rftoolsdim, thermaldynamics, thermalexpansion, thermalfoundation] at CLIENT
[11:34:30] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, codechickenlib, cofhcore, cofhworld, jei, journeymap, mcjtylib_ng, redstoneflux, rftools, rftoolsdim, thermaldynamics, thermalexpansion, thermalfoundation] at SERVER
[11:34:31] [Client thread/ERROR]: The mod redstoneflux is expecting signature 8a6abf2cb9e141b866580d369ba6548732eff25f for source RedstoneFlux-1.12-2.1.1.1-universal.jar, however there is no signature matching that description
[11:34:31] [Client thread/ERROR]: The mod cofhworld is expecting signature 8a6abf2cb9e141b866580d369ba6548732eff25f for source CoFHWorld-1.12.2-1.4.0.1-universal.jar, however there is no signature matching that description
[11:34:32] [Client thread/ERROR]: The mod thermalfoundation is expecting signature 8a6abf2cb9e141b866580d369ba6548732eff25f for source ThermalFoundation-1.12.2-2.6.7.1-universal.jar, however there is no signature matching that description
[11:34:32] [Client thread/ERROR]: The mod thermalexpansion is expecting signature 8a6abf2cb9e141b866580d369ba6548732eff25f for source ThermalExpansion-1.12.2-5.5.7.1-universal.jar, however there is no signature matching that description
[11:34:32] [Client thread/ERROR]: The mod thermaldynamics is expecting signature 8a6abf2cb9e141b866580d369ba6548732eff25f for source ThermalDynamics-1.12.2-2.5.6.1-universal.jar, however there is no signature matching that description
[11:34:32] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CodeChicken Lib, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:CoFH World, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:McJtyLib, FMLFileResourcePack:Redstone Flux, FMLFileResourcePack:RFTools, FMLFileResourcePack:RFTools Dimensions, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation
[11:34:32] [Client thread/INFO]: Processing ObjectHolder annotations
[11:34:32] [Client thread/INFO]: Found 1168 ObjectHolder annotations
[11:34:32] [Client thread/INFO]: Identifying ItemStackHolder annotations
[11:34:32] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[11:34:32] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[11:34:32] [Forge Version Check/INFO]: [thermaldynamics] Starting version check at https://raw.github.com/cofh/version/master/thermaldynamics_update.json
[11:34:33] [Forge Version Check/INFO]: [thermaldynamics] Found status: UP_TO_DATE Target: null
[11:34:33] [Forge Version Check/INFO]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[11:34:34] [Forge Version Check/INFO]: [codechickenlib] Starting version check at http://chickenbones.net/Files/notification/version.php?query=forge&version=1.12&file=CodeChickenLib
[11:34:34] [Client thread/INFO]: Registering default Feature Templates...
[11:34:34] [Client thread/INFO]: Registering default World Generators...
[11:34:34] [Client thread/INFO]: Verifying or creating base world generation directory...
[11:34:34] [Client thread/INFO]: Complete.
[11:34:34] [Client thread/INFO]: No plugins for JourneyMap API discovered.
[11:34:34] [Forge Version Check/INFO]: [codechickenlib] Found status: BETA Target: null
[11:34:34] [Forge Version Check/INFO]: [cofhworld] Starting version check at https://raw.github.com/cofh/version/master/cofhworld_update.json
[11:34:34] [Client thread/INFO]: RFTools Detected Dimensions addon: enabling support
[11:34:34] [Forge Version Check/INFO]: [cofhworld] Found status: UP_TO_DATE Target: null
[11:34:34] [Forge Version Check/INFO]: [thermalexpansion] Starting version check at https://raw.github.com/cofh/version/master/thermalexpansion_update.json
[11:34:35] [Forge Version Check/INFO]: [thermalexpansion] Found status: UP_TO_DATE Target: null
[11:34:35] [Forge Version Check/INFO]: [cofhcore] Starting version check at https://raw.github.com/cofh/version/master/cofhcore_update.json
[11:34:35] [Forge Version Check/INFO]: [cofhcore] Found status: UP_TO_DATE Target: null
[11:34:35] [Forge Version Check/INFO]: [thermalfoundation] Starting version check at https://raw.github.com/cofh/version/master/thermalfoundation_update.json
[11:34:35] [Forge Version Check/INFO]: [thermalfoundation] Found status: UP_TO_DATE Target: null
[11:34:36] [Client thread/INFO]: Could not read 'userbuilder.json', this is not an error!
[11:34:37] [Client thread/INFO]: OBJLoader: Domain rftools has been added.
[11:34:37] [Client thread/INFO]: Reading default dimlets.json
[11:34:37] [Client thread/INFO]: Registering rftools dimension type at id 2
[11:34:39] [Client thread/INFO]: Applying holder lookups
[11:34:39] [Client thread/INFO]: Holder lookups applied
[11:34:39] [Client thread/INFO]: Applying holder lookups
[11:34:39] [Client thread/INFO]: Holder lookups applied
[11:34:39] [Client thread/INFO]: Applying holder lookups
[11:34:39] [Client thread/INFO]: Holder lookups applied
[11:34:39] [Client thread/INFO]: Applying holder lookups
[11:34:39] [Client thread/INFO]: Holder lookups applied
[11:34:39] [Client thread/INFO]: Injecting itemstacks
[11:34:39] [Client thread/INFO]: Itemstack injection complete
[11:34:41] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:34:41] [Thread-5/INFO]: Initializing LWJGL OpenAL
[11:34:41] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:34:41] [Thread-5/INFO]: OpenAL initialized.
[11:34:41] [Sound Library Loader/INFO]: Sound engine started
[11:34:49] [Client thread/INFO]: Max texture size: 16384
[11:34:57] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[11:35:00] [Client thread/INFO]: Applying holder lookups
[11:35:00] [Client thread/INFO]: Holder lookups applied
[11:35:00] [Client thread/INFO]: Created: 256x128 textures-atlas
[11:35:00] [CC Supporters Downloader/INFO]: [codechicken.lib.internal.ModDescriptionEnhancer:lambda$init$0:85]: java.lang.UnsupportedOperationException: JsonNull
[11:35:00] [CC Supporters Downloader/INFO]: [codechicken.lib.internal.ModDescriptionEnhancer:lambda$init$0:85]: 	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
[11:35:00] [CC Supporters Downloader/INFO]: [codechicken.lib.internal.ModDescriptionEnhancer:lambda$init$0:85]: 	at codechicken.lib.internal.ModDescriptionEnhancer.parse(ModDescriptionEnhancer.java:103)
[11:35:00] [CC Supporters Downloader/INFO]: [codechicken.lib.internal.ModDescriptionEnhancer:lambda$init$0:85]: 	at codechicken.lib.internal.ModDescriptionEnhancer.lambda$init$0(ModDescriptionEnhancer.java:82)
[11:35:00] [CC Supporters Downloader/INFO]: [codechicken.lib.internal.ModDescriptionEnhancer:lambda$init$0:85]: 	at codechicken.lib.internal.ModDescriptionEnhancer$$Lambda$683/1124221755.run(Unknown Source)
[11:35:00] [CC Supporters Downloader/INFO]: [codechicken.lib.internal.ModDescriptionEnhancer:lambda$init$0:85]: 	at java.lang.Thread.run(Thread.java:745)
[11:35:00] [Client thread/INFO]: JourneyMap log initialized.
[11:35:00] [Client thread/INFO]: initialize ENTER
[11:35:01] [Client thread/WARN]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[11:35:01] [Client thread/WARN]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[11:35:01] [Client thread/INFO]: [ClientAPI] built with JourneyMap API 1.4
[11:35:01] [Client thread/INFO]: Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[11:35:01] [Client thread/INFO]: initialize EXIT, elapsed count 0 avg ?ms
[11:35:01] [Client thread/INFO]: [mcjty.lib.font.TrueTypeFont:<init>:119]: TrueTypeFont loaded: java.awt.Font[family=Ubuntu,name=Ubuntu,style=plain,size=40] - AntiAlias = false
[11:35:01] [Client thread/INFO]: Received RFTools dimension manager request from mod 'rftools'
[11:35:01] [Client thread/INFO]: Injecting itemstacks
[11:35:01] [Client thread/INFO]: Itemstack injection complete
[11:35:02] [Client thread/ERROR]: Couldn't locate icons for Default: C:\Users\utente\Documents\Curse\Minecraft\Instances\test%20RFTOOL\mods\journeymap-1.12.2-5.7.1.jar\assets\journeymap\icon\entity
[11:35:02] [Client thread/INFO]: Added entity icons from journeymap:icon/entity. Success: false
[11:35:02] [Client thread/ERROR]: Couldn't locate icons for flat: C:\Users\utente\Documents\Curse\Minecraft\Instances\test%20RFTOOL\mods\journeymap-1.12.2-5.7.1.jar\assets\journeymap\theme\flat
[11:35:02] [Client thread/INFO]: Preloaded theme textures: 0
[11:35:02] [Client thread/INFO]: CoFH Core: Load Complete.
[11:35:02] [Client thread/INFO]: Accumulating world generation files from: "C:\Users\utente\Documents\Curse\Minecraft\Instances\test RFTOOL\config\cofh\world"
[11:35:02] [Client thread/INFO]: Found a total of 3 world generation files.
[11:35:02] [Client thread/INFO]: Reading world generation info from: "cofh\world\01_thermalfoundation_ores.json":
[11:35:02] [Client thread/INFO]: Reading world generation info from: "cofh\world\02_thermalfoundation_oil.json":
[11:35:02] [Client thread/INFO]: Reading world generation info from: "cofh\world\03_thermalfoundation_clathrates.json":
[11:35:02] [Client thread/INFO]: CoFH World: Load Complete.
[11:35:02] [Client thread/INFO]: Starting JEI...
[11:35:03] [Client thread/INFO]: Registering recipe categories...
[11:35:03] [Client thread/INFO]: Registering recipe categories took 209.7 ms
[11:35:03] [Client thread/INFO]: Registering mod plugins...
[11:35:03] [Client thread/INFO]: Registering mod plugins took 334.1 ms
[11:35:03] [Client thread/INFO]: Building recipe registry...
[11:35:03] [Client thread/INFO]: Building recipe registry took 166.5 ms
[11:35:03] [Client thread/INFO]: Building ingredient list...
[11:35:03] [Client thread/INFO]: Building ingredient list took 47.72 ms
[11:35:03] [Client thread/INFO]: Building ingredient filter...
[11:35:04] [Client thread/INFO]: Building ingredient filter took 217.3 ms
[11:35:04] [Client thread/INFO]: Building bookmarks...
[11:35:04] [Client thread/INFO]: Building bookmarks took 3.456 ms
[11:35:04] [Client thread/INFO]: Building runtime...
[11:35:04] [Client thread/INFO]: Building runtime took 82.95 ms
[11:35:04] [Client thread/INFO]: Optimizing memory usage...
[11:35:04] [Client thread/INFO]: Optimizing memory usage took 73.37 ms
[11:35:04] [Client thread/INFO]: Starting JEI took 1.361 s
[11:35:04] [Client thread/INFO]: [Whitelist] Reading established Whitelist from file.
[11:35:04] [Client thread/INFO]: Thermal Foundation: Load Complete.
[11:35:04] [Client thread/INFO]: Thermal Expansion: Load Complete.
[11:35:04] [Client thread/INFO]: Thermal Dynamics: Load Complete.
[11:35:04] [Client thread/INFO]: Forge Mod Loader has successfully loaded 16 mods
[11:35:04] [Client thread/WARN]: Skipping bad option: lastServer:
[11:35:04] [Client thread/INFO]: Narrator library for x64 successfully loaded
[11:35:14] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[11:35:14] [Server thread/INFO]: Generating keypair
[11:35:14] [Server thread/INFO]: Preparing all world data
[11:35:14] [Server thread/INFO]: Injecting existing registry data into this server instance
[11:35:15] [Server thread/INFO]: Applying holder lookups
[11:35:15] [Server thread/INFO]: Holder lookups applied
[11:35:15] [Server thread/INFO]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@41a5d410)
[11:35:16] [Server thread/INFO]: Loaded 497 advancements
[11:35:16] [Server thread/INFO]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@41a5d410)
[11:35:16] [Server thread/INFO]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@41a5d410)
[11:35:16] [Server thread/INFO]: Preparing start region for level 0
[11:35:17] [Server thread/INFO]: Preparing spawn area: 33%
[11:35:17] [Server thread/INFO]: RFTools: server is starting
[11:35:17] [Server thread/INFO]: Registering RFTools dimensions: 
[11:35:18] [Server thread/INFO]: Unloading dimension -1
[11:35:18] [Server thread/INFO]: Unloading dimension 1
[11:35:18] [Server thread/INFO]: Changing view distance to 12, from 10
[11:35:20] [Netty Local Client IO #0/INFO]: Server protocol version 2
[11:35:20] [Netty Server IO #1/INFO]: Client protocol version 2
[11:35:20] [Netty Server IO #1/INFO]: Client attempting to join with 16 mods : minecraft@1.12.2,FML@8.0.99.99,thermalexpansion@5.5.7,rftoolsdim@5.71,thermaldynamics@2.5.6,redstoneflux@2.1.1,cofhworld@1.4.0,rftools@7.73,jei@4.16.1.301,cofhcore@4.6.6,mcjtylib_ng@3.5.4,forge@14.23.5.2855,thermalfoundation@2.6.7,codechickenlib@3.2.3.358,mcp@9.42,journeymap@1.12.2-5.7.1
[11:35:20] [Netty Server IO #1/INFO]: Skipping config sync, No mods have registered a syncable config.
[11:35:20] [Netty Local Client IO #0/INFO]: [Netty Local Client IO #0] Client side modded connection established
[11:35:20] [Server thread/INFO]: [Server thread] Server side modded connection established
[11:35:20] [Server thread/INFO]: dani6102[local:E:57515a00] logged in with entity id 291 at (36.600814260368196, 108.16235065145206, 101.9607970321757)
[11:35:20] [Server thread/INFO]: SMP: Sync dimensions to client
[11:35:20] [Netty Local Client IO #0/INFO]: DimensionSyncPacket: Registering: 
[11:35:20] [Client thread/INFO]: Received dimension information from server
[11:35:20] [Server thread/INFO]: dani6102 joined the game
[11:35:20] [Server thread/INFO]: SMP: Player logged in: Sync diminfo to clients
[11:35:20] [Server thread/INFO]: Send dimlet rules to the client
[11:35:20] [Server thread/INFO]: Rules packet size: 5779 of 8192
[11:35:21] [Server thread/INFO]: Saving and pausing game...
[11:35:21] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[11:35:22] [Client thread/INFO]: Received dimlet rules from server
[11:35:23] [Client thread/WARN]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[11:35:23] [Client thread/WARN]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[11:35:23] [Client thread/INFO]: Loaded 0 waypoints from C:\Users\utente\Documents\Curse\Minecraft\Instances\test RFTOOL\journeymap\data\sp\New World\waypoints
[11:35:23] [Client thread/INFO]: Mapping started in C:\Users\utente\Documents\Curse\Minecraft\Instances\test RFTOOL\journeymap\data\sp\New World\DIM0. Memory: 991MB total, 494MB free 
[11:35:23] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
[11:35:23] [Client thread/INFO]: JourneyMap: Press [J]
[11:35:36] [Server thread/INFO]: Saving and pausing game...
[11:35:36] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[11:35:40] [Netty Local Client IO #0/INFO]: Client disconnected from server
[11:35:40] [Netty Local Client IO #0/INFO]: Cleaning up RFTools dimensions
[11:35:40] [Client thread/INFO]: Mapping halted in C:\Users\utente\Documents\Curse\Minecraft\Instances\test RFTOOL\journeymap\data\sp\New World\DIM0
[11:35:40] [Server thread/INFO]: Stopping server
[11:35:40] [Server thread/INFO]: Saving players
[11:35:40] [Server thread/INFO]: dani6102 lost connection: Disconnected
[11:35:40] [Server thread/INFO]: dani6102 left the game
[11:35:40] [Server thread/INFO]: Stopping singleplayer server as player logged out
[11:35:40] [Server thread/INFO]: Saving worlds
[11:35:40] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[11:35:40] [Server thread/INFO]: Unloading dimension 0
[11:35:41] [Server thread/INFO]: Applying holder lookups
[11:35:41] [Server thread/INFO]: Holder lookups applied
[11:35:41] [Server thread/INFO]: Cleaning up all world data: 0 data blobs
[11:35:41] [Server thread/INFO]: RFTools Dimensions: server is stopping. Shutting down gracefully
[11:35:45] [Client thread/INFO]: Stopping!
[11:35:45] [Client thread/INFO]: SoundSystem shutting down...
[11:35:45] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by McJty** [comment]
That's normal. There are too many dimlets so they are not shown in JEI (only the basic ones). You have to use the dimlet workbench to see them all
