### ISSUE TITLE
crash a la connection

### ISSUE THREAD

**Issue by ulyssedu45** [McJty/RFTools#230]
Bonjour/bonsoir il mes impossible de rejoindre mon serveur (timed out)

log de connexion

[19:29:33] [Client thread/ERROR]: ########## GL ERROR ##########
[19:29:33] [Client thread/ERROR]: @ Post render
[19:29:33] [Client thread/ERROR]: 1281: Invalid value
[19:29:38] [Netty Client IO #10/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[19:29:38] [Netty Client IO #10/INFO] [MineMenu]: CLIENT: Disconnected from server, enabling all click actions
[19:29:38] [Netty Client IO #10/INFO] [Galacticraft]: Unregistered Dimension: -30
[19:29:38] [Netty Client IO #10/INFO] [Galacticraft]: Unregistered Dimension: -29
[19:29:38] [Netty Client IO #10/INFO] [Galacticraft]: Unregistered Dimension: -28
[19:29:38] [Netty Client IO #10/INFO] [mcjty.rftools.RFTools]: Disconnect from server: Unregistering RFTools dimensions
[19:29:38] [Netty Client IO #10/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientDisconnectionFromServerEvent@e1bde36:
java.lang.NullPointerException
	at mcjty.rftools.dimension.RfToolsDimensionManager.unregisterDimensions(RfToolsDimensionManager.java:96) ~[RfToolsDimensionManager.class:?]
	at mcjty.rftools.ClientDisconnectEvent.onDisconnectedFromServerEvent(ClientDisconnectEvent.java:13) ~[ClientDisconnectEvent.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_830_ClientDisconnectEvent_onDisconnectedFromServerEvent_ClientDisconnectionFromServerEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.close(NetworkDispatcher.java:405) [NetworkDispatcher.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeClose(DefaultChannelHandlerContext.java:560) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.close(DefaultChannelHandlerContext.java:545) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.close(DefaultChannelHandlerContext.java:423) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:826) [DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:177) [AbstractChannel.class:?]
	at net.minecraft.network.NetworkManager.func_150718_a(NetworkManager.java:230) [ej.class:?]
	at net.minecraft.network.NetworkManager.exceptionCaught(NetworkManager.java:104) [ej.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.exceptionCaught(NetworkDispatcher.java:487) [NetworkDispatcher.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:61) [ChannelHandlerAdapter.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:61) [ChannelHandlerAdapter.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:61) [ChannelHandlerAdapter.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeExceptionCaught(DefaultChannelHandlerContext.java:275) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireExceptionCaught(DefaultChannelHandlerContext.java:253) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:185) [ReadTimeoutHandler.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler$ReadTimeoutTask.run(ReadTimeoutHandler.java:211) [ReadTimeoutHandler$ReadTimeoutTask.class:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [PromiseTask$RunnableAdapter.class:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123) [ScheduledFutureTask.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[19:29:38] [Netty Client IO #10/ERROR] [FML]: Index: 4 Listeners:
[19:29:38] [Netty Client IO #10/ERROR] [FML]: 0: NORMAL
[19:29:38] [Netty Client IO #10/ERROR] [FML]: 1: ASM: dmillerw.menu.network.NetworkEventHandler@35b0206a onClientDisconnect(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientDisconnectionFromServerEvent;)V
[19:29:38] [Netty Client IO #10/ERROR] [FML]: 2: ASM: openperipheral.addons.glasses.TerminalManagerClient$FmlBusListener@6b6d8f17 onDisconnect(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientDisconnectionFromServerEvent;)V
[19:29:38] [Netty Client IO #10/ERROR] [FML]: 3: ASM: micdoodle8.mods.galacticraft.core.network.ConnectionEvents@6374eac6 onConnectionClosed(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientDisconnectionFromServerEvent;)V
[19:29:38] [Netty Client IO #10/ERROR] [FML]: 4: ASM: mcjty.rftools.ClientDisconnectEvent@1ff41594 onDisconnectedFromServerEvent(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientDisconnectionFromServerEvent;)V
[19:29:38] [Netty Client IO #10/ERROR] [FML]: 5: ASM: openmods.network.IdSyncManager@5736c7fa onDisconnect(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientDisconnectionFromServerEvent;)V
[19:29:38] [Client thread/INFO] [journeymap]: Mapping halted in c:\ftb\FTBHorizonsII\minecraft\journeymap\data\mp\Minecraft~Server\DIM0
[19:29:38] [Client thread/INFO] [FML]: Applying holder lookups
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup chisel:arcane for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.arcane. Is there something wrong with the registry?
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup chisel:thaumium for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.thaumium. Is there something wrong with the registry?
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup chisel:tallow for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.tallow. Is there something wrong with the registry?
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup Railcraft:routing.ticket.gold for public static net.minecraft.item.Item openperipheral.integration.railcraft.TicketItemHolder.ticketGold. Is there something wrong with the registry?
[19:29:38] [Client thread/WARN] [FML]: Unable to lookup Railcraft:routing.ticket for public static net.minecraft.item.Item openperipheral.integration.railcraft.TicketItemHolder.ticket. Is there something wrong with the registry?
[19:29:38] [Client thread/INFO] [FML]: Holder lookups applied
[19:29:40] [Client thread/INFO] [Mekanism]: VoiceServer: Stopping client connection...
[19:29:40] [Client thread/INFO] [Mekanism]: Finished loading Cardboard Box blacklist (loaded 0 entries)
[19:29:40] [Client thread/INFO] [Mekanism]: Reloaded config.
[19:29:41] [Client thread/ERROR]: ########## GL ERROR ##########
[19:29:41] [Client thread/ERROR]: @ Post render
[19:29:41] [Client thread/ERROR]: 1281: Invalid value

**Comment by McJty** [comment]
Please english next time. My french is very bad. But anyway, I don't think this crash is related to RFTools. I see a 'GL ERROR' in your log. I think something is wrong on the graphics side. I see nothing in the log that indicates this is an RFTools problem though.

You can reopen this ticket if you think it is RFTools related after all.

Thanks,

**Comment by ulyssedu45** [comment]
sorry but my English is zero (google translation)

but I'm sure it's from rftools

pastebin : http://pastebin.com/9v2nSKyF

**Comment by McJty** [comment]
This crashlog indicates a problem with the FluidRegistry (liquids). RFTools does not use this but there are indeed problems with other mods and the fluid registry. I recommend you update Forge and all your mods because many mods had to be rewritten recently due to the fluid registry.

Again, not an RFTools problem.

**Comment by ulyssedu45** [comment]
thank you what the mod vien?
For I had to remove the extra utilities modpack ftb
because it makes the server to crash demarage.
