### ISSUE TITLE
Clicking "Gui style" buttons drops client from server

### ISSUE THREAD

**Issue by NoX-programer** [McJty/RFTools#274]
After updating to 3.21 I've noticed that this happens. If u can't reproduce, I can give logs & info.

**Comment by McJty** [comment]
Works fine for me so I would appreciate a full client log.

**Comment by NoX-programer** [comment]
Client log contain no errors, but server console... http://dl.netlocal.ru/mc/.logs/rft_server-log.txt.zip

**Comment by McJty** [comment]
I really need the full log. Including things that are no errors. It is all relevant to find out what is wrong here.

**Comment by NoX-programer** [comment]
Ok, here is it: http://dl.netlocal.ru/mc/.logs/rft_client-log.zip

**Comment by McJty** [comment]
Still not the right one. The real log is MUCH larger. I'm talking about fml-client-latest.log

**Comment by NoX-programer** [comment]
That's strange. Seems to be my client is not writing it. It's just latest.log in .minecraft\logs and archive of previous logs.

**Comment by McJty** [comment]
hmm. Without that information I'm a bit blind I'm afraid. Can you try again and see if a log is generated then? Thanks

**Comment by NoX-programer** [comment]
Still the same. Server have fml-server-latest.log, but not client (I mean fml-client-latest.log).

**Comment by McJty** [comment]
Yes, but the client should have the fml-client-latest.log. Perhaps you should describe a bit what you're doing exactly? It sounds like you're using a server? What about the log on the client side? How are you starting MC? What version of Java?

Without logs I'm going to need more detailed information.

BTW. You have mcjtylib1.1.0 right? But you hopefully didn't forget to remove an older version of mcjtylib if you have it? Also server and client are both using same version?

**Comment by NoX-programer** [comment]
I've updated from 3.11, when no mcjtylib is needed and of course have removed previous version from server and client. I've checked that in singleplayer, it happens. And one and only log present, latest log, have
[00:36:47] [Client thread/INFO]: net.minecraft.client.gui.inventory.GuiContainerCreative
[00:36:47] [Client thread/INFO]: net.minecraft.client.gui.inventory.GuiContainerCreative$ContainerCreative
[00:36:59] [Client thread/INFO]: mcjty.rftools.blocks.crafter.GuiCrafter
[00:36:59] [Client thread/INFO]: mcjty.rftools.blocks.crafter.CrafterContainer
[00:37:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at mcjty.network.PacketSetGuiStyle.onMessage(PacketSetGuiStyle.java:40) ~[PacketSetGuiStyle.class:?]
	at mcjty.network.PacketSetGuiStyle.onMessage(PacketSetGuiStyle.java:14) ~[PacketSetGuiStyle.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
...

And, still REALLY no fml-client-latest.log. I can share the screen via skype :)
MC starting with official client launcher v.1.6.19. Java:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Server also have mcjtylib-1.1.0.jar and prev version deleted. Anything else?

**Comment by McJty** [comment]
Oh Java 1.8.0_25. Please upgrade that to a more recent Java8. There were problems with that version of Java. Let me know if that helps.

**Comment by NoX-programer** [comment]
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

It is not helps, even on singleplayer.

**Comment by McJty** [comment]
Well then I have no clue. Others have not reported any errors with latest rftools and mcjtylib. Without a more detailed log I'm afraid there isn't much I can do :-(

**Comment by McJty** [comment]
Ok, seems I can reproduce this after all. I'll work on a fix. Sorry for bothering you about logs :-)

**Comment by NoX-programer** [comment]
Not a problem, I glad to help.

**Comment by McJty** [comment]
Will be fixed in next release (probably 3.30)
