### ISSUE TITLE
Teleporting crashes the server

### ISSUE THREAD

**Issue by Saereth** [McJty/RFTools#304]
Anytime you dial.. anywhere and teleport it crashes the server with this error:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 26/08/15 14:16
Description: Ticking block entity

java.lang.ArithmeticException: / by zero
        at mcjty.rftools.blocks.teleporter.TeleportationTools.consumeReceiverEnergy(TeleportationTools.java:250)
        at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:135)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:488)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:349)
        at mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:51)
        at net.minecraft.world.World.func_72939_s(World.java:2513)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at mcjty.rftools.blocks.teleporter.TeleportationTools.consumeReceiverEnergy(TeleportationTools.java:250)
        at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:135)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:488)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:349)
        at mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:51)

-- Block entity being ticked --
Details:
        Name: MatterTransmitterTileEntity // mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity
        Block type: ID #3222 (tile.matterTransmitterBlock // mcjty.rftools.blocks.teleporter.MatterTransmitterBlock)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-273,86,164), Chunk: (at 15,5,4 in -18,10; contains blocks -288,0,160 to -273,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Actual block type: ID #3222 (tile.matterTransmitterBlock // mcjty.rftools.blocks.teleporter.MatterTransmitterBlock)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2513)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
        Level name: world
        All players: 3 total; [EntityPlayerMP['Thundra'/87320, l='world', x=-263.76, y=88.98, z=192.77](Thundra at -263.75585035950314,88.9800208015675,192.76729382796364), EntityPlayerMP['Somebody3lse'/126499, l='world', x=-315.84, y=9$
        Chunk stats: ServerChunkCache: 315 Drop: 0
        Level seed: 8744727102674645199
        Level generator: ID 04 - ATG, ver 0. Features enabled: true
        Level generator options:
        Level spawn location: World: (-278,86,180), Chunk: (at 10,5,4 in -18,11; contains blocks -288,0,176 to -273,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Level time: 1756768 game time, 5622627 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 15483 (now: false), thunder time: 67960 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)

**Comment by Saereth** [comment]
Rftools 3.33, forge 1448. Happy to provide any additional information.

**Comment by McJty** [comment]
Did you perhaps reconfigure rftools to need no RF on the receiver side? That's the only way this can happen.

**Comment by Saereth** [comment]
Yep, setting it to 1 stops the crashes, Thanks!

**Comment by McJty** [comment]
I have already fixed it so that 0 works too. For next version.
