### ISSUE TITLE
[BUG] MineTweaker + RFT crash

### ISSUE THREAD

**Issue by hron84** [McJty/RFTools#306]
I'm not sure it's a RFT or MT bug, but after saving the world, I cannot load it again until I restart the whole game. Maybe somebody does not close something correctly? Idk.

```
[17:25:52] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
java.lang.NullPointerException
	at mcjty.rftools.items.dimlets.KnownDimletConfiguration.getDimletKey(KnownDimletConfiguration.java:1329) ~[KnownDimletConfiguration.class:?]
	at mcjty.rftools.items.dimlets.KnownDimlet.func_77667_c(KnownDimlet.java:160) ~[KnownDimlet.class:?]
	at mcjty.rftools.items.dimlets.KnownDimlet.func_77653_i(KnownDimlet.java:170) ~[KnownDimlet.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at minetweaker.mc1710.recipes.MCRecipeManager$ActionAddRecipe.describeUndo(MCRecipeManager.java:387) ~[MCRecipeManager$ActionAddRecipe.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:82) ~[MTTweaker.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:589) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166) ~[MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.2.1291-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:809) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:91) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

Forge: 1448
RFTools: rftools-3.33.jar
MineTweaker: MineTweaker3-1.7.10-3.0.9C.jar

**Comment by McJty** [comment]
What pack is this and how are the recipes modified?

**Comment by hron84** [comment]
Pathfinder (FTB 3rdparty pack), and as I see some dimlet recipes are modified...

**Comment by McJty** [comment]
Hmm, you upgraded rftools manually then?

**Comment by hron84** [comment]
Yep, as I mentioned in #305 there was a _lot_ of crash because of rftools, and I also lost not just one save because world become not-loading after crashing during teleporting to a new RFT dim.
