### ISSUE TITLE
No rain dimlet causes crash

### ISSUE THREAD

**Issue by acutelypsychotic** [McJty/RFTools#317]
When I add the No Rain Dimlet (the only dimlet I used) my server crashes as soon as the builder finishes constructing the dimension. I can reboot the server and log back in but when I try to dial to that dimension it crashes also. I can once again reboot and the dialer will be dialed to that dimension but when I step into the transmitter it crashes and I am stuck in that dimension and get continuous crashes when I try to log in. I can't replicate this crash in single player, only server.

---- Minecraft Crash Report ----
// Don't do that.

Time: 9/3/15 1:27 AM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.world.World.func_72894_k(F)V
	at mcjty.rftools.dimension.world.GenericWorldProvider.updateWeather(GenericWorldProvider.java:358)
	at net.minecraft.world.World.func_72979_l(World.java:2692)
	at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:979)
	at net.minecraft.world.World.func_72835_b(World.java:2669)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:137)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mcjty.rftools.dimension.world.GenericWorldProvider.updateWeather(GenericWorldProvider.java:358)
	at net.minecraft.world.World.func_72979_l(World.java:2692)
	at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:979)
	at net.minecraft.world.World.func_72835_b(World.java:2669)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:137)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 4 Drop: 1
	Level seed: -2962957997543156653
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 832430032 bytes (793 MB) / 1056309248 bytes (1007 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 7 total; -Xms1G -Xmx4G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	rftools{3.34} [RFTools] (rftools-3.34.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['acutelypsychotic'/184, l='world', x=116.63, y=72.00, z=256.29]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by McJty** [comment]
Will be fixed in next version.
