### ISSUE TITLE
v 3.40 with Highlands compatibility issue 

### ISSUE THREAD

**Issue by katur239** [McJty/RFTools#336]
After upgrading to v 3.40 I get this error when trying to gen a new world. I reverted to 3.35 and it works.  So I am guessing it is something in the new changes.

Description: Exception generating new chunk
 
java.lang.NullPointerException: Exception generating new chunk
        at mcjty.rftools.ForgeEventHandlers.onReplaceBiomeBlocks(ForgeEventHandlers.java:287)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_914_ForgeEventHandlers_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at highlands.overworld.ChunkProviderHLOverworld.replaceBlocksForBiome(ChunkProviderHLOverworld.java:226)
        at highlands.overworld.ChunkProviderHLOverworld.func_73154_d(ChunkProviderHLOverworld.java:261)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
        at net.minecraft.world.World.func_72964_e(World.java:419)
        at net.minecraft.world.World.func_147439_a(World.java:345)
        at net.minecraft.world.World.func_147437_c(World.java:365)
        at net.minecraft.world.World.func_147474_b(World.java:329)
        at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
        at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
        at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
        at WorldServerOF.func_72963_a(WorldServerOF.java:80)
        at net.minecraft.world.World.<init>(World.java:260)
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
        at WorldServerOF.<init>(WorldServerOF.java:69)
        at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
        at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

FULL ERROR: http://pastebin.com/KsnZPpDR

**Comment by McJty** [comment]
Will fix in 3.41 (preparing hotfix release now)
