### ISSUE TITLE
Cannot join into my server

### ISSUE THREAD

**Issue by AlexPlus117** [McJty/RFTools#364]
Hi McJty,
I can't join into my modded server anymore and the client log shows this: http://pastebin.com/qwfQbQJc

**Comment by McJty** [comment]
I need to see the entire full log

**Comment by AlexPlus117** [comment]
Here's that: https://dl.dropboxusercontent.com/u/237928521/fml-client-latest.log

**Comment by McJty** [comment]
This is not an RFTools problem. RFTools just crashes because something else already corrupted the system. I'm not sure exactly what is wrong but at about 40% in your log file I find this:

[00:00:50] [Client thread/ERROR] [FML/]: FluidIdRegistryMessageHandler exception
java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.loadFluidDefaults(FluidRegistry.java:117) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidRegistry.initFluidIDs(FluidRegistry.java:82) ~[FluidRegistry.class:?]
	at net.minecraftforge.common.network.FluidIdRegistryMessageHandler.channelRead0(FluidIdRegistryMessageHandler.java:15) ~[FluidIdRegistryMessageHandler.class:?]
	at net.minecraftforge.common.network.FluidIdRegistryMessageHandler.channelRead0(FluidIdRegistryMessageHandler.java:11) ~[FluidIdRegistryMessageHandler.class:?]


So it appears one of the mods you have is doing something wrong with fluid handling (an area that RFTools doesn't touch). Maybe you added/updated some mod and something got incompatible or so?

**Comment by AlexPlus117** [comment]
I've just disable Binnie's mods and all works now.
