### ISSUE TITLE
buggy&crashy mob tp using builder

### ISSUE THREAD

**Issue by NoX-programer** [McJty/RFTools#371]
The bug occurs when you trying to teleport a mob not so far away. For example, setup small space chamber 4x4 (internal: 2x2) and place builder about a chunk away, put the card into, turn on "Entities are moved", give red signal and try to teleport a mob. You will see that mob isn't teleported, but you cannot do anything with it. After teleport away&back or relogin to server you will see mob teleported and mob is real. Looks like some desync with server, even in singleplayer.
The crash happens if you try to teleport an enderman from enderworld using builder. There is 2 conditions: enderman and from ender to overworld. I tested it on server - got server crash:

[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:981) ~[oi.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.teleportEntity(BuilderTileEntity.java:1302) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.moveEntities(BuilderTileEntity.java:1259) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.handleBlock(BuilderTileEntity.java:966) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:630) ~[BuilderTileEntity.class:?]
	at mcjty.lib.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:51) ~[GenericTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2512) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) ~[MinecraftServer.class:?]
	... 4 more
[08:39:57] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:981) ~[oi.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.teleportEntity(BuilderTileEntity.java:1302) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.moveEntities(BuilderTileEntity.java:1259) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.handleBlock(BuilderTileEntity.java:966) ~[BuilderTileEntity.class:?]
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:630) ~[BuilderTileEntity.class:?]
	at mcjty.lib.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:51) ~[GenericTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2512) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

Same crash on client btw. Client was crashed when I tried to teleport a cow from the end.

Version: RFTools-4.01.

**Comment by McJty** [comment]
Should be fixed in next release
