### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by LatentDesire** [McJty/RFTools#398]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/30/15 7:59 PM
Description: Initializing game

java.lang.RuntimeException
	at cpw.mods.fml.common.registry.VillagerRegistry.registerVillagerId(VillagerRegistry.java:125)
	at mcjty.rftools.village.VillageSetup.villagerSetup(VillageSetup.java:12)
	at mcjty.rftools.CommonProxy.init(CommonProxy.java:121)
	at mcjty.rftools.ClientProxy.init(ClientProxy.java:24)
	at mcjty.rftools.RFTools.init(RFTools.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.registry.VillagerRegistry.registerVillagerId(VillagerRegistry.java:125)
	at mcjty.rftools.village.VillageSetup.villagerSetup(VillageSetup.java:12)
	at mcjty.rftools.CommonProxy.init(CommonProxy.java:121)
	at mcjty.rftools.ClientProxy.init(ClientProxy.java:24)
	at mcjty.rftools.RFTools.init(RFTools.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262605200 bytes (250 MB) / 564310016 bytes (538 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHI	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHI	llibrary{0.6.1} [LLibrary] (llibrary-0.6.1-1.7.10.jar) 
	UCHI	mowziesmobs{1.2.5-undefined} [Mowzie's Mobs] (123.Mowzie's Mobs-1.2.5.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHI	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHI	AntMan{Beta-1.7.10-1.5.4} [AntMan] (AntMan-Beta-1.7.10-1.5.4.jar) 
	UCHI	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHI	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UCHI	cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
	UCHI	thedalekmod{39.75} [The Dalek Mod] (Dalek_Mod_1710.jar) 
	UCHI	darkcore{0.3} [Dark Core] (darkcore-0.3-45.jar) 
	UCHI	ElecCore{1.4.176} [ElecCore] (ElecCore-1.7.10-1.4.176.jar) 
	UCHI	deepresonance{1.1.2} [DeepResonance] (deepresonance-1.1.2.jar) 
	UCHI	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHI	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHI	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHI	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHI	fossil{1.7.10 Build 7.2.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.jar) 
	UCHI	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHI	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHI	kcweaponmod{0.1.3} [KC's Weapon Mod v0.1.3] (KCs Weapon Mod v0.1.3 (MC 1.7.10) (Weap v1.1).zip) 
	UCHI	halocraft{0.7.4} [Halocraft v0.7.4] (Halocraft v0.7.4 (MC 1.7.10) (KCWM Weap v1.1).zip) 
	UCHI	killerchief_halocraft{0.7.0} [HalocraftOldIDUpdater] (Halocraft v0.7.4 (MC 1.7.10) (KCWM Weap v1.1).zip) 
	UCHI	malisiscore{1.7.10-0.13.1} [MalisisCore] (malisiscore-1.7.10-0.13.1.jar) 
	UCHI	malisisdoors{1.7.10-1.12.2} [Malisis' Doors] (malisisdoors-1.7.10-1.12.2.jar) 
	UCHI	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHI	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UCHI	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHI	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.7.10-1.9.jar) 
	UCHI	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar) 
	UCHI	starwarsmod{1.1.1} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.1.1.jar) 
	UCHI	quantumflux{1.7.10-1.3.1} [QuantumFlux] (QuantumFlux-1.7.10-1.3.1.jar) 
	UCHE	rftools{4.12} [RFTools] (rftools-4.12.jar) 
	UCHI	SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
	UCHI	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCHI	superMassiveTech{0.2.0-alpha} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.2.0-alpha-86.jar) 
	UCHI	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) 
	UCHI	TardisMod{0.99} [Tardis Mod] (tardismod-1.7.10-0.99-207.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHI	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHI	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHI	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHI	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHI	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCHI	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '1.4.0 - Build 8.14.10.2093' Renderer: 'Intel Pineview Platform'
	CoFHCore: -[1.7.10]3.0.3-303
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel Pineview Platform GL version 1.4.0 - Build 8.14.10.2093, Intel
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is supported, EXT_blend_func_separate is supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Anisotropic filtering is supported and maximum anisotropy is 4.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by LatentDesire** [comment]
Recently added some new mods. Not sure with which it is clashing.

**Comment by McJty** [comment]
This is a villager id conflict. Simply change the id of the villager in the rftools config to some other number (it is 10 by default)

**Comment by LatentDesire** [comment]
Got it . Thanks.
