### ISSUE TITLE
Ticking Block Entity Crash when entering Dim with Builder running as Silk Quarry

### ISSUE THREAD

**Issue by Aoxmodeus** [McJty/RFTools#436]
Getting this consistently.

Set up a builder with a clearing silk quarry card.  512, 256, 512 region, offset to quarry from sky to bedrock.  Work great, super fast.  Skips hives and draconic ore, but I can deal with that.  However, I'm consistently getting a crash if I log out for the day, and come back to what I assume is a finished quarry.  I get a ticking block entity on the builder when entering the dimesion, resetting the minecraf t instance. If the quarry hasn't finished yet, I'll sometimes get a ticking block entity, the server will crash, and when it comes back up, I'm able to get back into the dimension. If the quarry has (I assume, I've never been able to get in to check) finished, just consistent crash.  I've worked around this by removing my player data, coming back to the server, shutting down the dimesion, and rebuilding it with a different digit.  I suppose I could use the EIO quarry, but I'd rather use the speedy RFTools builder for that.  One caveat, the builder has two tesseracts on it, one for items and energy, the other for just energy.  Perhaps that's causing this. Additionally, I'm keeping the builder itself loaded with a Railcraft Admin Anchor. Here's the basic bits of the crashlog: 

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 1/28/16 2:22 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:187)
	at net.minecraft.item.ItemStack.func_77985_e(ItemStack.java:192)
	at mcjty.lib.container.InventoryHelper.mergeItemStackInternal(InventoryHelper.java:58)
	at mcjty.lib.container.InventoryHelper.mergeItemStackSafe(InventoryHelper.java:38)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.checkAndInsertItems(BuilderTileEntity.java:1127)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.checkAndInsertItems(BuilderTileEntity.java:1112)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.silkQuarryBlock(BuilderTileEntity.java:973)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:888)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:797)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:661)
	at mcjty.rftools.blocks.spaceprojector.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:682)
	at mcjty.lib.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:50)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by McJty** [comment]
Can't reproduce this but I did a blind fix that should hopefully fix this for 4.21 (soon to be released)

**Comment by lAimBotl** [comment]
I recently crashed too, i shift r-clicked the builder clicked 2 points around 100 blocks from each other and tried to swap to the sphere shape since i wanted to make a sphere shield, but crashed. *Confirmed in latest release* weird it did not give me a crash report, but it gave me a log thing in the main folder.
[Crash log thing.txt](https://github.com/McJty/RFTools/files/1036646/Crash.log.thing.txt)

**Comment by lAimBotl** [comment]
maybe I should make my own issue . . . not sure if you will see this in a closed thread. . .
