### ISSUE TITLE
[1.8] Crash setting power storage to "out" via GUI

### ISSUE THREAD

**Issue by Daenyth** [McJty/RFTools#460]
I was playing around in a test world, and I set a linked power block to "out" with the gui button, and it immediately crashed.

This is on version 1.8.9-4.21beta16

```
[06:57:28] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152) ~[bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at mcjty.rftools.apideps.RFToolsDimensionChecker.isRFToolsDimension(RFToolsDimensionChecker.java:15) ~[RFToolsDimensionChecker.class:?]
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.calculateBlobDistance(PowerCellNetwork.java:139) ~[PowerCellNetwork$Network.class:?]
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.updateCostFactor(PowerCellNetwork.java:177) ~[PowerCellNetwork$Network.class:?]
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.calculateCostFactor(PowerCellNetwork.java:226) ~[PowerCellNetwork$Network.class:?]
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.sendOutEnergy(PowerCellTileEntity.java:175) ~[PowerCellTileEntity.class:?]
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.func_73660_a(PowerCellTileEntity.java:148) ~[PowerCellTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1716) ~[adm.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
	... 4 more
[06:57:28] [Server thread/ERROR]: This crash report has been saved to: /Applications/MultiMC.app/Contents/MacOS/instances/1.8.9/minecraft/crash-reports/crash-2016-02-21_06.57.28-server.txt
[06:57:28] [Server thread/INFO]: Stopping server
[06:57:28] [Server thread/INFO]: Saving players
[06:57:28] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 2/21/16 6:57 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mcjty.rftools.apideps.RFToolsDimensionChecker.isRFToolsDimension(RFToolsDimensionChecker.java:15)
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.calculateBlobDistance(PowerCellNetwork.java:139)
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.updateCostFactor(PowerCellNetwork.java:177)
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.calculateCostFactor(PowerCellNetwork.java:226)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.sendOutEnergy(PowerCellTileEntity.java:175)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.func_73660_a(PowerCellTileEntity.java:148)
	at net.minecraft.world.World.func_72939_s(World.java:1716)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mcjty.rftools.apideps.RFToolsDimensionChecker.isRFToolsDimension(RFToolsDimensionChecker.java:15)
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.calculateBlobDistance(PowerCellNetwork.java:139)
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.updateCostFactor(PowerCellNetwork.java:177)
	at mcjty.rftools.blocks.powercell.PowerCellNetwork$Network.calculateCostFactor(PowerCellNetwork.java:226)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.sendOutEnergy(PowerCellTileEntity.java:175)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.func_73660_a(PowerCellTileEntity.java:148)

-- Block entity being ticked --
Details:
	Name: powercell // mcjty.rftools.blocks.powercell.PowerCellTileEntity
	Block type: ID #715 (tile.powercell // mcjty.rftools.blocks.powercell.PowerCellBlock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-151,68,-186), Chunk: (at 9,4,6 in -10,-12; contains blocks -160,0,-192 to -145,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #715 (tile.powercell // mcjty.rftools.blocks.powercell.PowerCellBlock)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1716)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/172, l='Test', x=-152.84, y=68.00, z=-185.58]]
	Chunk stats: ServerChunkCache: 773 Drop: 0
	Level seed: -3934825344772383730
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -188.00,64.00,4.00 - World: (-188,64,4), Chunk: (at 4,4,4 in -12,0; contains blocks -192,0,0 to -177,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 75711 game time, 3436 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 46463 (now: false), thunder time: 13194 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1033401328 bytes (985 MB) / 2227175424 bytes (2124 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms2048m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1746-universal.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-16} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-16.jar) 
	UCHIJAAAA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJAAAA	chiselsandbits{mc1.8.9-v1.8.6} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.6.jar) 
	UCHIJAAAA	craftingtweaks{3.0.41} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.41.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	graves{1.8.9-b31-universal} [Graves Mod] (graves-1.8.9-b31-universal.jar) 
	UCHIJAAAA	Harvest{1.8.9-1.0.0-2} [Harvest] (Harvest-1.8.9-1.0.0-2.jar) 
	UCHIJAAAA	inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks] (InventoryTweaks-1.60-beta-30.jar) 
	UCHIJAAAA	ironbackpacks{1.8-1.0.7} [Iron Backpacks] (IronBackpacks-1.8-1.0.7.jar) 
	UCHIJAAAA	IronChest{6.0.121.768} [Iron Chest] (ironchest-1.8.9-6.0.121.768.jar) 
	UCHIJAAAA	JEI{2.26.0.154} [Just Enough Items] (jei_1.8.9-2.26.0.154.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
	UCHIJAAAA	JEIAddons{0.11.2.56} [Just Enough Items Addons] (JEIAddons_1.8.9-0.11.2.56.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
	UCHIJAAAA	Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
	UCHIJAAAA	progressiveautomation{1.6.34} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.34.jar) 
	UCHIJAAAA	rftools{4.21beta16} [RFTools] (rftools-1.8.9-4.21beta16.jar) 
	UCHIJAAAA	rftoolsdim{4.21beta18} [RFTools Dimensions] (rftoolsdim-1.8.9-4.21beta18.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.4.0} [Storage Drawers] (StorageDrawers-1.8.9-2.4.0.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2 (1).jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/172, l='Test', x=-152.84, y=68.00, z=-185.58]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[06:57:28] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Contents/MacOS/instances/1.8.9/minecraft/crash-reports/crash-2016-02-21_06.57.28-server.txt
[06:57:28] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[06:57:28] [Server thread/INFO]: Saving worlds
[06:57:28] [Server thread/INFO]: Saving chunks for level 'Test'/Overworld
[06:57:28] [Netty Local Client IO #0/INFO] [THAUMCRAFT]: Restoring client configs.
[06:57:28] [Server thread/INFO]: Saving chunks for level 'Test'/Nether
[06:57:28] [Server thread/INFO]: Saving chunks for level 'Test'/The End
[06:57:28] [Server thread/INFO]: Saving chunks for level 'Test'/The Outer Lands
[06:57:28] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 0
[06:57:28] [Server thread/INFO] [journeymap]: Mapping halted in /Applications/MultiMC.app/Contents/MacOS/instances/1.8.9/minecraft/journeymap/data/sp/Test/DIM0
[06:57:28] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[06:57:28] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 1
[06:57:28] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -42
[06:57:28] [Server thread/INFO] [FML]: Unloading dimension 0
[06:57:28] [Server thread/INFO] [FML]: Unloading dimension -1
[06:57:28] [Server thread/INFO] [FML]: Unloading dimension 1
[06:57:28] [Server thread/INFO] [FML]: Unloading dimension -42
[06:57:28] [Server thread/INFO] [FML]: Applying holder lookups
[06:57:28] [Server thread/INFO] [FML]: Holder lookups applied
[06:57:28] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[06:57:28] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[06:57:28] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up RFTools dimensions
[06:57:28] [Server thread/INFO] [mcjty.lib.varia.Logging]:     Unregister dimension: 2
[06:57:28] [Server thread/INFO] [mcjty.lib.varia.Logging]:     Unregister dimension: 3
[06:57:28] [Server thread/INFO] [mcjty.lib.varia.Logging]:     Unregister dimension: 4
[06:57:28] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[06:57:28] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
```

**Comment by Daenyth** [comment]
I can't load the world now, it crashes when I open it.

**Comment by Daenyth** [comment]
Upgrading to 4.22 lets me load the world

**Comment by McJty** [comment]
Yes, this bug was fixed
