### ISSUE TITLE
Liquid Absorber absorbs water and when I try to remove it this happens:

### ISSUE THREAD

**Issue by Kazzamkablam** [McJty/RFTools#462]
Version: rftoolsdim-1.8.9-4.22beta25.jar

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at mcjty.rftoolsdim.blocks.absorbers.LiquidAbsorberBlock.addInformation(LiquidAbsorberBlock.java:62)
	at mcjty.lib.container.GenericItemBlock.func_77624_a(GenericItemBlock.java:21)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:587)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:132)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:165)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:49)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:305)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1104)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by McJty** [comment]
Ok. I will check this out. Thanks for reporting

**Comment by McJty** [comment]
Fixed next release
