### ISSUE TITLE
[1.8.9] crash when putting a screen in front of a brick block [multiplayer]

### ISSUE THREAD

**Issue by winsrp** [McJty/RFTools#469]
So in a multiplayer server, 

If you make a 2 block tall column with normal cobble bricks (yes 2 blocks one on top of the other), and put a screen in any X,Y facing face of the 2nd block (the one on top) it crashes the game.

```
 [Netty Server IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_74]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_74]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_74]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_74]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_74]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:4.0.23.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:4.0.23.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:4.0.23.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by McJty** [comment]
I need a lot more information. What version of rftools? Also the entire log would be useful

**Comment by winsrp** [comment]
well that was the full log, that's the weird thing. using version 1.8.9-4.22beta31

Every time I did the same thing the same error occurred.

**Comment by McJty** [comment]
That can't be the full log. In your logs folder there should be a much bigger log. BTW. Does the server crash? In that case I need the log from the server. If the client crashes I need the big log in your logs folder of the client.

**Comment by McJty** [comment]
I mean a log called 'latest.log' in your logs folder (or on server side if the server crashes)

**Comment by winsrp** [comment]
The server does not crash, only the client, but no client can log after that error, I need to remove the plugin, load the server, remove the brick behind the screen, and then reload the server with your mod.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/14/16 9:21 AM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:887)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:853)
	at ConnectedTextures.getConnectedTextureHorizontal(ConnectedTextures.java:938)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:409)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:180)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:101)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:261)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:116)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:66)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:287)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1333)
	at shadersmod.client.ShadersRender.setupTerrain(ShadersRender.java:55)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1640)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1537)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1322)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:887)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:853)
	at ConnectedTextures.getConnectedTextureHorizontal(ConnectedTextures.java:938)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:409)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:180)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:101)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:261)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:116)

-- Block model being tesselated --
Details:
	Block: minecraft:stonebrick[variant=stonebrick]
	Block location: World: (-44,66,129), Chunk: (at 4,4,1 in -3,8; contains blocks -48,0,128 to -33,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:66)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:52)

-- Block being tesselated --
Details:
	Block type: ID #98 (tile.stonebricksmooth // net.minecraft.block.BlockStoneBrick)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-44,66,129), Chunk: (at 4,4,1 in -3,8; contains blocks -48,0,128 to -33,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:287)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1333)
	at shadersmod.client.ShadersRender.setupTerrain(ShadersRender.java:55)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1640)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1537)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['winsrp'/198, l='MpServer', x=-43.55, y=65.00, z=132.31]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 84.00,64.00,252.00 - World: (84,64,252), Chunk: (at 4,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 318809 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: true. Cheats: false
	Forced entities: 58 total; [EntitySheep['Sheep'/0, l='MpServer', x=-106.25, y=63.00, z=148.84], EntityRabbit['Rabbit'/1, l='MpServer', x=-89.75, y=63.00, z=175.13], EntityRabbit['Rabbit'/3, l='MpServer', x=-90.78, y=63.00, z=165.13], EntityRabbit['Rabbit'/4, l='MpServer', x=-91.75, y=63.00, z=170.66], EntityBat['Bat'/5, l='MpServer', x=-82.85, y=58.00, z=172.48], EntityRabbit['Rabbit'/6, l='MpServer', x=-82.41, y=63.00, z=171.41], EntityBat['Bat'/7, l='MpServer', x=-83.56, y=27.09, z=179.25], EntityBat['Bat'/8, l='MpServer', x=-78.31, y=43.07, z=178.37], EntityRabbit['Rabbit'/9, l='MpServer', x=-81.75, y=64.00, z=180.50], EntityBat['Bat'/10, l='MpServer', x=-71.75, y=51.85, z=54.25], EntityBat['Bat'/11, l='MpServer', x=-70.11, y=18.02, z=124.51], EntityPlayerSP['winsrp'/198, l='MpServer', x=-43.55, y=65.00, z=132.31], EntityOwl['Owl'/12, l='MpServer', x=-64.56, y=68.00, z=131.56], EntitySquid['Squid'/13, l='MpServer', x=-70.44, y=58.00, z=157.28], EntityOwl['Owl'/14, l='MpServer', x=-69.56, y=68.00, z=171.53], EntityRabbit['Rabbit'/15, l='MpServer', x=-71.59, y=64.00, z=178.88], EntityOwl['Owl'/16, l='MpServer', x=-73.47, y=71.00, z=181.53], EntityOwl['Owl'/17, l='MpServer', x=-65.56, y=71.00, z=178.41], EntityBat['Bat'/19, l='MpServer', x=-78.53, y=17.71, z=79.98], EntityRabbit['Rabbit'/20, l='MpServer', x=-48.22, y=68.00, z=84.84], EntityBat['Bat'/21, l='MpServer', x=-53.59, y=54.10, z=125.22], EntityCreeper['Creeper'/22, l='MpServer', x=-58.03, y=52.00, z=120.56], EntityItem['item.item.owlEgg'/23, l='MpServer', x=-62.09, y=65.00, z=132.06], EntityRabbit['Rabbit'/26, l='MpServer', x=-34.09, y=66.00, z=94.34], EntityBat['Bat'/27, l='MpServer', x=-33.25, y=16.10, z=105.63], EntityBat['Bat'/28, l='MpServer', x=-41.75, y=13.90, z=121.60], EntityBat['Bat'/33, l='MpServer', x=-19.50, y=28.49, z=78.40], EntityRabbit['Rabbit'/34, l='MpServer', x=-27.50, y=63.00, z=84.88], EntityOwl['Owl'/36, l='MpServer', x=-20.50, y=72.00, z=104.56], EntityRabbit['Rabbit'/37, l='MpServer', x=-27.31, y=66.00, z=165.66], EntityOwl['Owl'/38, l='MpServer', x=-27.50, y=71.00, z=162.47], EntityOwl['Owl'/39, l='MpServer', x=-29.59, y=70.00, z=162.38], EntityOwl['Owl'/40, l='MpServer', x=-29.44, y=73.00, z=172.53], EntityOwl['Owl'/41, l='MpServer', x=-10.56, y=70.00, z=188.47], EntityOwl['Owl'/43, l='MpServer', x=-18.59, y=67.00, z=192.47], EntityRabbit['Rabbit'/52, l='MpServer', x=0.34, y=63.00, z=56.38], EntityBat['Bat'/53, l='MpServer', x=-13.28, y=50.10, z=87.75], EntityPig['Pig'/54, l='MpServer', x=-0.47, y=63.00, z=124.91], EntityOwl['Owl'/55, l='MpServer', x=-10.56, y=68.00, z=157.44], EntityOwl['Owl'/56, l='MpServer', x=-6.56, y=70.00, z=147.56], EntityRabbit['Rabbit'/57, l='MpServer', x=4.13, y=63.00, z=173.84], EntityItem['item.item.owlEgg'/58, l='MpServer', x=-8.88, y=68.00, z=189.13], EntityOwl['Owl'/59, l='MpServer', x=-15.59, y=68.03, z=190.78], EntityRabbit['Rabbit'/63, l='MpServer', x=2.28, y=63.00, z=125.28], EntityRabbit['Rabbit'/64, l='MpServer', x=1.28, y=63.00, z=124.28], EntityOwl['Owl'/65, l='MpServer', x=-2.08, y=73.73, z=114.81], EntityRabbit['Rabbit'/66, l='MpServer', x=3.00, y=63.00, z=144.19], EntityOwl['Owl'/67, l='MpServer', x=7.47, y=69.00, z=153.47], EntityOwl['Owl'/68, l='MpServer', x=19.53, y=80.00, z=193.41], EntityOwl['Owl'/69, l='MpServer', x=17.19, y=82.00, z=190.94], EntityItem['item.item.owlEgg'/70, l='MpServer', x=18.84, y=82.00, z=190.88], EntitySheep['Sheep'/199, l='MpServer', x=-108.59, y=63.00, z=144.81], EntityOwl['Owl'/71, l='MpServer', x=20.47, y=80.00, z=189.44], EntitySheep['Sheep'/200, l='MpServer', x=-109.19, y=64.00, z=132.47], EntityItem['item.item.owlEgg'/72, l='MpServer', x=20.13, y=80.00, z=189.09], EntityOwl['Owl'/73, l='MpServer', x=17.53, y=82.00, z=191.56], EntityBat['Bat'/74, l='MpServer', x=20.95, y=31.15, z=193.20], EntityItem['item.item.owlEgg'/75, l='MpServer', x=19.25, y=80.00, z=193.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 941016016 bytes (897 MB) / 2154344448 bytes (2054 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1762 Optifine OptiFine_1.8.9_HD_U_H4_pre 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1762.jar) 
	UCHIJA	Forge{11.15.1.1762} [Minecraft Forge] (forge-1.8.9-11.15.1.1762.jar) 
	UCHIJA	darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJA	AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
	UCHIJA	MovingWorld{MC1.8.9-INDEV-H} [Moving World] (movingworld-MC1.8.9-INDEV-H-full.jar) 
	UCHIJA	ArchimedesShipsPlus{MC1.8.9-INDEV-G} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8.9-INDEV-G.jar) 
	UCHIJA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJA	bdlib{1.10.0.29} [BD Lib] (bdlib-1.10.0.29-mc1.8.9.jar) 
	UCHIJA	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UCHIJA	BetterFoliage{2.0.3} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.3.jar) 
	UCHIJA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1926-universal.jar) 
	UCHIJA	bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
	UCHIJA	caterpillar{0.0.0} [Caterpillar] (Caterpillar-1.2.189b76.jar) 
	UCHIJA	cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0-mc1.8.9.jar) 
	UCHIJA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJA	EnderZoo{1.8.9-1.1.3.35} [Ender Zoo] (EnderZoo-1.8.9-1.1.3.35.jar) 
	UCHIJA	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCHIJA	reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
	UCHIJA	fluxedredstone{1.3.0.31} [FluxedRedstone] (Fluxed Redstone-1.3.0.31.jar) 
	UCHIJA	substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
	UCHIJA	foundry{1.4.0.0} [Foundry] (Foundry-1.8.9-1.4.0.0.jar) 
	UCHIJA	furnus{1.72} [Furnus] (Furnus-1.8.9-1.72.jar) 
	UCHIJA	pressure{1.3.0.22} [Pressure Pipes] (pressure-1.3.0.22-mc1.8.9.jar) 
	UCHIJA	advgenerators{0.9.19.8} [Advanced Generators] (generators-0.9.19.8-mc1.8.9.jar) 
	UCHIJA	inventorytweaks{1.60-beta-38-b8950ce} [Inventory Tweaks] (InventoryTweaks-1.60-beta-38.jar) 
	UCHIJA	ironbackpacks{1.8-1.0.7} [Iron Backpacks] (IronBackpacks-1.8-1.0.7.jar) 
	UCHIJA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJA	JEI{2.28.5.172} [Just Enough Items] (jei_1.8.9-2.28.5.172.jar) 
	UCHIJA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJA	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
	UCHIJA	MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar) 
	UCHIJA	MissingRecipies{0.1.0} [MissingRecipies] (Missing Recipes 0.1.jar) 
	UCHIJA	MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
	UCHIJA	cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
	UCHIJA	neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
	UCHIJA	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UCHIJA	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UCHIJA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJA	rftools{4.22beta31} [RFTools] (rftools-1.8.9-4.22beta31.jar) 
	UCHIJA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJA	wuppy29_simplerecipes{1.9.0} [Simple Recipes] (Simple Recipes 1.8.0-1.9.0.jar) 
	UCHIJA	SpiceOfLife{1.3.1} [The Spice of Life] (SpiceOfLife-mc1.8.9-1.3.1.jar) 
	UCHIJA	StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
	UCHIJA	storagenetwork{1.8.0} [Storage Network] (StorageNetwork-1.8.9-1.8.0.jar) 
	UCHIJA	usefulrecipes{1.1} [UsefulRecipes] (UsefulRecipes-1.1.0(1.8.9).jar) 
	UCHIJA	usefulstones{0.2} [Useful Stones] (UsefulStones_0.2-MCv1.8.9.jar) 
	UCHIJA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJA	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)
  
CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	List of loaded APIs: 
		* AppleCoreAPI (2.0.0) from AppleCore-mc1.8.9-1.3.0.jar
		* BetterAchievements|API (0.1.1) from BetterAchievements-1.8.9-0.1.1.jar
		* CoFHAPI (1.8.9R1.2.0B1) from Foundry-1.8.9-1.4.0.0.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Bookshelf-API-1.8.9-2.3.6.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* foundry.api (1.4.0.0) from Foundry-1.8.9-1.4.0.0.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.5.172.jar
		* McJtyLib (1.8.9-1.8.1beta8) from mcjtylib-1.8.9-1.8.1beta8.jar
		* pressureAPI (1.3.0.22) from pressure-1.3.0.22-mc1.8.9.jar
		* reborncoreAPI (1.4.3.20) from RebornCore-1.8.9-1.4.3.20-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
		* WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1762
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Invictus-2.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H4_pre
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1.13 BETA - Ultra.zip
	OpenGlVersion: 4.5.0 NVIDIA 358.91
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by McJty** [comment]
It is actually crashing in better foliage. Better report to them

**Comment by winsrp** [comment]
oh... werid, thanks I will let them know.
