### ISSUE TITLE
1.9 1805+ forge , lots of mods are crashing at launch

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#482]
this is definitely not the only mod crashing, I saw major changes made in this version. Probably affecting a lot of mods.

**Comment by McJty** [comment]
I need a lot more information then this. What version of rftools, what kind of crash, ...

**Comment by LordHellscream** [comment]
Sorry, using the latest version of rftool and the mcjty lib. Crashing happened at loading screen of minecraft (not the launcher).

**Comment by McJty** [comment]
Log?

**Comment by LordHellscream** [comment]
the crash actually happened when it says on the screen "loading rftools", but even without the mod, the game would still crash (but at later stage, like loading world). Anyhow this is the log (with rftools).

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/25/16 2:36 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class mezz.jei.config.LocalizedConfiguration
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:172)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class mezz.jei.config.LocalizedConfiguration
	at mezz.jei.config.LocalizedConfiguration.getStringList(LocalizedConfiguration.java:92)
	at mezz.jei.config.Config.syncItemBlacklistConfig(Config.java:304)
	at mezz.jei.config.Config.preInit(Config.java:211)
	at mezz.jei.ProxyCommonClient.preInit(ProxyCommonClient.java:58)
	at mezz.jei.JustEnoughItems.preInit(JustEnoughItems.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:128)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 64625200 bytes (61 MB) / 276287488 bytes (263 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1809 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1809-1.9.jar) 
	UCH	Forge{12.16.0.1809} [Minecraft Forge] (forge-1.9-12.16.0.1809-1.9.jar) 
	UCH	armorplus{1.6} [ArmorPlus] (ArmorPlus-1.7(1.9).jar) 
	UCH	cobblepopper{1.0.1} [Cobble Popper] (cobblepopper-1.9-1.0.1-5-universal.jar) 
	UCE	JEI{3.0.6.169} [Just Enough Items] (jei_1.9-3.0.6.169.jar) 
	UCH	journeymap{1.9-5.1.5b3} [JourneyMap] (journeymap-1.9-5.1.5b3-unlimited.jar) 
	UCH	lit{1.9-1.0.0} [Little Insignificant Things] (LittleInsignificantThings-1.9-1.0.0.jar) 
	UCH	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-4.jar) 
	UCH	progressiveautomation{1.6.36} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.36.jar) 
	UCH	quantumflux{2.0.2} [QuantumFlux] (quantumflux-1.9-2.0.2.jar) 
	UCH	RandomUtilities{3.0.0} [Random Utilities] (Random Utilities-1.9-3.0.0.jar) 
	UCH	rftools{4.23beta34} [RFTools] (rftools-1.9.0-4.23beta34.jar) 
	UCH	storagesilo{1.2.2} [StorageSilo] (storagesilo-1.9-1.2.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.91' Renderer: 'GeForce GTX 970/PCIe/SSE2'

**Comment by LordHellscream** [comment]
Based on Forge update: 

Build 1.9-12.16.0.1805-1.9:
	fry: Cleanup: removed IEEP, removed redundant casts, fixed imports, fixed typos.
	fry: Fixed isSideSolid causing infinite loops due to the call to getActualState.
	fry: Removed LanguageRegistry and CollectionWrapperFactory.
	fry: Removed RenderWorldEvent, encapsulated all public event fields.
	**fry: Made some more public fields either private or final.**

May be this is causing the access error? Just a thought.

**Comment by McJty** [comment]
Seems like a bug in JEI. Report this to them
