### ISSUE TITLE
[1.9] Crash if respawning on top of a shield set to solid/damage for players

### ISSUE THREAD

**Issue by WardBenjamin** [McJty/RFTools#508]
Here's a stack trace:

net.minecraft.util.ReportedException: Exception while adding particle
	at net.minecraft.world.World.updateEntities(World.java:1895) ~[World.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1880) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1114) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:401) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.isValid(World.java:250) ~[World.class:?]
	at net.minecraft.world.World.getTileEntity(World.java:2547) ~[World.class:?]
	at mcjty.rftools.blocks.shield.SolidShieldBlock$1.colorMultiplier(SolidShieldBlock.java:36) ~[SolidShieldBlock$1.class:?]
	at net.minecraft.client.renderer.color.BlockColors.colorMultiplier(BlockColors.java:150) ~[BlockColors.class:?]
	at net.minecraft.client.particle.EntityDiggingFX.func_187154_b(EntityDiggingFX.java:66) ~[EntityDiggingFX.class:?]
	at net.minecraft.client.particle.EntityDiggingFX.func_174845_l(EntityDiggingFX.java:59) ~[EntityDiggingFX.class:?]
	at net.minecraft.client.particle.EntityDiggingFX$Factory.getEntityFX(EntityDiggingFX.java:126) ~[EntityDiggingFX$Factory.class:?]
	at net.minecraft.client.particle.EffectRenderer.spawnEffectParticle(EffectRenderer.java:137) ~[EffectRenderer.class:?]
	at net.minecraft.client.renderer.RenderGlobal.spawnEntityFX(RenderGlobal.java:2150) ~[RenderGlobal.class:?]
	at net.minecraft.client.renderer.RenderGlobal.spawnParticle(RenderGlobal.java:2105) ~[RenderGlobal.class:?]
	at net.minecraft.world.World.spawnParticle(World.java:1165) ~[World.class:?]
	at net.minecraft.world.World.spawnParticle(World.java:1152) ~[World.class:?]
	at net.minecraft.entity.Entity.createRunningParticles(Entity.java:1271) ~[Entity.class:?]
	at net.minecraft.entity.Entity.spawnRunningParticles(Entity.java:1257) ~[Entity.class:?]
	at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:507) ~[Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:252) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:427) ~[Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2078) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:252) ~[EntityPlayer.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:199) ~[EntityPlayerSP.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2086) ~[World.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2051) ~[World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1882) ~[World.class:?]
	... 21 more

**Comment by McJty** [comment]
What version of forge? This could be a bug in forge btw

**Comment by WardBenjamin** [comment]
This is using Forge 1865 (1.9-12.16.0.1865).

**Comment by McJty** [comment]
I worked around it for next version
