### ISSUE TITLE
Dimensions not saving their Power upon restart

### ISSUE THREAD

**Issue by Tridon343** [McJty/RFTools#523]
I am on rf tools dimension  beta 37 (rftoolsdim-1.9.0-4.23beta37)

Whenever I shut down my singleplayer world and restart the dimensions loose their power buffer. Haven't tested loggin out while standing in one dimension yet, base is still in the overworld.

otherwise things have been pretty neat!

**Comment by McJty** [comment]
That's weird. I have no idea how that could even happen...

**Comment by Kazzamkablam** [comment]
Can confirm, just happened to me too, lost about 10 million power on empty dimension.

**Comment by Kazzamkablam** [comment]
I did some testing with the issue and when I tried to re-enter dimension with zero power this happened:


java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.World.func_72907_a(World.java:3118)
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_177458_a(GenericChunkGenerator.java:510)
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:301)
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:238)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:126)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

Forge log:
http://www.filedropper.com/fml-client-latest_1

Hope that helps

**Comment by McJty** [comment]
Thanks I will check this out

**Comment by McJty** [comment]
That last crash is probably fixed next release. Not sure about the powerloss. Could possibly be related but not sure

**Comment by McJty** [comment]
Or hmm. It might not be fixed. Could you do a right click with the dimension tab of that dimension in your hand and give me that information?

**Comment by Kazzamkablam** [comment]
https://imgur.com/6IcAWhT

For shift click info on dimension tab

**Comment by McJty** [comment]
Was fixed some time ago
