### ISSUE TITLE
[1.9] RFTools assumes the client is infallible and always has worldObj initialized on the client

### ISSUE THREAD

**Issue by asiekierka** [McJty/RFTools#534]
Which it doesn't since 1.8! Surprising, I know! (You probably need more null checks.)

Time: 5/14/16 9:19 AM
Description: Tesselating block model
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=intermediate, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at mcjty.rftools.blocks.logic.LogicTileEntity.getFacing(LogicTileEntity.java:11)
	at mcjty.rftools.blocks.logic.LogicSlabBlock.func_185496_a(LogicSlabBlock.java:61)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:422)
	at net.minecraft.block.Block.func_176225_a(Block.java:369)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185894_c(BlockStateContainer.java:402)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:113)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:84)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:45)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:36)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:196)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:99)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:42)
	at java.lang.Thread.run(Thread.java:745)
A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by asiekierka** [comment]
Global Forge issue for the problem: https://github.com/MinecraftForge/MinecraftForge/issues/2855

**Comment by iTitus** [comment]
Can confirm: http://pastebin.com/KU27MuNz

**Comment by McJty** [comment]
Fixed next release. Do you need this urgently?

**Comment by asiekierka** [comment]
No. But I'd like to have it sometime today.

2016-05-14 14:36 GMT+02:00 McJty <notifications@github.com>:
