### ISSUE TITLE
[1.10-5.06] Crash when trying to teleport and then moving away

### ISSUE THREAD

**Issue by cri5ti** [McJty/RFTools#629]
Modpack: FTB Unstable 4.2.3
This occurs quite often in this modpack, probably since the release of the modpack about a month ago. I usually patch the `isPlayerOutsideBeam` with some more null checks around the player.

```
java.lang.NullPointerException: Ticking block entity
	at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.isPlayerOutsideBeam(MatterTransmitterTileEntity.java:537)
	at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:345)
	at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.func_73660_a(MatterTransmitterTileEntity.java:308)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```
https://gist.github.com/cri5ti/40ffab334b1ac795c20c536f57fd095b

**Comment by McJty** [comment]
Was fixed in recent versions of rftools
