### ISSUE TITLE
Crash when using syringe on a wither skeleton

### ISSUE THREAD

**Issue by cryptrol** [McJty/RFTools#716]
On 1.10.2, experienced a crash when using a syringe on a wither skeleton.

```
[18:19:22] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ee.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128) ~[dr.class:?]
	at mcjty.rftools.items.SyringeItem.onLeftClickEntity(SyringeItem.java:108) ~[SyringeItem.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:938) ~[ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1217) ~[zs.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:526) ~[blm.class:?]
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by cryptrol** [comment]
I have tried to reproduce it and can't. Feel free to close this issue.

**Comment by McJty** [comment]
I will check it out in any case. Maybe I can find something

**Comment by McJty** [comment]
I cannot reproduce it either but I added a protection in case it ever happens again
