### ISSUE TITLE
[1.10] Sometimes crash when withdrawing items from remote storage module.

### ISSUE THREAD

**Issue by Daenyth** [McJty/RFTools#732]
Full log here: https://gist.github.com/Daenyth/ec702806f8c526b7a816a2606a8815ca

This happened once when getting IC2 empty fluid cells, and I believe the other time I saw it, it was also an IC2 item, if that matters.

Relevant bit, I believe

```
[21:06:09] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1713) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_91]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_91]
	at mcjty.lib.gui.widgets.WidgetList.mouseRelease(WidgetList.java:265) ~[WidgetList.class:?]
	at mcjty.lib.gui.widgets.Panel.mouseRelease(Panel.java:98) ~[Panel.class:?]
	at mcjty.lib.gui.widgets.Panel.mouseRelease(Panel.java:93) ~[Panel.class:?]
	at mcjty.lib.gui.Window.mouseMovedOrUp(Window.java:79) ~[Window.class:?]
	at mcjty.lib.gui.WindowManager.lambda$mouseReleased$9(WindowManager.java:135) ~[WindowManager.class:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_91]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_91]
	at mcjty.lib.gui.WindowManager.mouseReleased(WindowManager.java:135) ~[WindowManager.class:?]
	at mcjty.lib.container.GenericGuiContainer.func_146286_b(GenericGuiContainer.java:236) ~[GenericGuiContainer.class:?]
	at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.func_146286_b(GuiStorageScanner.java:240) ~[GuiStorageScanner.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558) ~[bft.class:?]
	at mcjty.lib.container.GenericGuiContainer.func_146274_d(GenericGuiContainer.java:226) ~[GenericGuiContainer.class:?]
	at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.func_146274_d(GuiStorageScanner.java:234) ~[GuiStorageScanner.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) ~[bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) ~[bcx.class:?]
	... 9 more
```

**Comment by McJty** [comment]
What version of RFTools and McJtyLib?

**Comment by Daenyth** [comment]
rftools 5.22 and mcjtylib 2.0.0

**Comment by McJty** [comment]
Upgrade McJtyLib to 2.0.1. I recently fixed this bug there

**Comment by Daenyth** [comment]
Thanks
