### ISSUE TITLE
[1.10] NPE adding OpenComp item to Filter Module

### ISSUE THREAD

**Issue by Daenyth** [McJty/RFTools#745]
I opened a new Filter Module, set it to whitelist, match only on mod, and I clicked into the grid with an OpenComputers Trading upgrade.

rftools 5.22
mcjtylib 2.02
opencomputers 1.6.0.3-rc1

```
[21:07:57] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1713) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at mcjty.rftools.items.storage.StorageFilterInventory.func_70296_d(StorageFilterInventory.java:93) ~[StorageFilterInventory.class:?]
	at mcjty.rftools.items.storage.StorageFilterInventory.func_70299_a(StorageFilterInventory.java:83) ~[StorageFilterInventory.class:?]
	at mcjty.lib.container.GhostSlot.func_75215_d(GhostSlot.java:42) ~[GhostSlot.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
	at mcjty.lib.container.GenericContainer.func_184996_a(GenericContainer.java:283) ~[GenericContainer.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550) ~[blm.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630) ~[bgl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:596) ~[bgl.class:?]
	at mcjty.lib.container.GenericGuiContainer.func_146286_b(GenericGuiContainer.java:237) ~[GenericGuiContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558) ~[bft.class:?]
	at mcjty.lib.container.GenericGuiContainer.func_146274_d(GenericGuiContainer.java:228) ~[GenericGuiContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) ~[bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) ~[bcx.class:?]
	... 9 more
```

**Comment by McJty** [comment]
Fixed next release
