### ISSUE TITLE
This is not a JSON Array

### ISSUE THREAD

**Issue by LuciDuki** [McJty/RFTools#795]
Hi.

After is restartet the Server while creating a new dimension i got following error:

java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[JsonElement.class:?]
	at mcjty.rftools.items.dimlets.KnownDimletConfiguration.readUserDimlets(KnownDimletConfiguration.java:1043) ~[KnownDimletConfiguration.class:?]
	at mcjty.rftools.items.dimlets.KnownDimletConfiguration.init(KnownDimletConfiguration.java:759) ~[KnownDimletConfiguration.class:?]
	at mcjty.rftools.items.dimlets.KnownDimletConfiguration.init(KnownDimletConfiguration.java:425) ~[KnownDimletConfiguration.class:?]
	at mcjty.rftools.WorldLoadEvent.loadEvent(WorldLoadEvent.java:23) ~[WorldLoadEvent.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1031_WorldLoadEvent_loadEvent_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

Server crashes after them.

Minecraft Version: 1.7.10
Forge Version: 1614
RFTools Version: 4.23

If you need additional information pls ask me :)

Thank you

**Comment by LuciDuki** [comment]
Problem solved!


Userdimlets.json was misconfigured

**Comment by GoldArdeo** [comment]
> Problem solved!
> 
> Userdimlets.json was misconfigured

bit late but can you elaborate if at all possible?

**Comment by MichaelHillcox** [comment]
The json file likely was malformed meaning something was wrong. If you're having this, run your json file through a json validator (google) and see if you've got errors.
