### ISSUE TITLE
[1.10.2][ RFTOOLS 1.10-5.55/5.57] Crash on crafter tier3 with Mekanism basic universal cable craft

### ISSUE THREAD

**Issue by ddrmax** [McJty/RFTools#812]
step to reproduce: put the craft of the basic universal cable on a tier 3 crafter
type of error: instant crash and instant crash when reloading the world
modpack skyexchange
mekanism version : lastest (.292)

cash log
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.53.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 30/10/16 13:33
Description: Tesselating block model

java.lang.ClassCastException: net.minecraft.block.state.BlockStateContainer$StateImplementation cannot be cast to net.minecraftforge.common.property.IExtendedBlockState
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:118)
	at com.rwtema.extrautils2.backend.ModifyingBakedModel.func_188616_a(ModifyingBakedModel.java:41)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at com.rwtema.extrautils2.tile.TileCrafter.render(TileCrafter.java:439)
	at com.rwtema.extrautils2.tile.tesr.XUTESRHook.render(XUTESRHook.java:29)
	at com.rwtema.extrautils2.tile.tesr.XUTESRBase.renderTileEntityFast(XUTESRBase.java:56)
	at com.rwtema.extrautils2.tile.tesr.XUTESRBase.renderTileEntityAt(XUTESRBase.java:37)
	at com.rwtema.extrautils2.tile.tesr.XUTESRBase.func_180535_a(XUTESRBase.java:16)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:700)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:118)
	at com.rwtema.extrautils2.backend.ModifyingBakedModel.func_188616_a(ModifyingBakedModel.java:41)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)

-- Block model being tesselated --
Details:
	Block: minecraft:air
	Block location: World: (104,67,208), Chunk: (at 8,4,0 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at com.rwtema.extrautils2.tile.TileCrafter.render(TileCrafter.java:439)
	at com.rwtema.extrautils2.tile.tesr.XUTESRHook.render(XUTESRHook.java:29)
	at com.rwtema.extrautils2.tile.tesr.XUTESRBase.renderTileEntityFast(XUTESRBase.java:56)
	at com.rwtema.extrautils2.tile.tesr.XUTESRBase.renderTileEntityAt(XUTESRBase.java:37)
	at com.rwtema.extrautils2.tile.tesr.XUTESRBase.func_180535_a(XUTESRBase.java:16)

-- Block Entity Details --
Details:
	Name: XU2:TileCrafter // com.rwtema.extrautils2.tile.TileCrafter
	Block type: ID #941 (tile.ExtraUtils2:Crafter // com.rwtema.extrautils2.blocks.BlockCrafter)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (104,66,208), Chunk: (at 8,4,0 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #941 (tile.ExtraUtils2:Crafter // com.rwtema.extrautils2.blocks.BlockCrafter)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:700)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ddrmax'/4728, l='MpServer', x=106,20, y=65,00, z=209,51]]
	Chunk stats: MultiplayerChunkCache: 583, 583
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (104,64,220), Chunk: (at 8,4,12 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3271526 game time, 1625275 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityZombie['Zombie'/4723, l='MpServer', x=110,15, y=40,00, z=211,21], EntityCreeper['Creeper'/4724, l='MpServer', x=110,40, y=40,00, z=212,16], EntityBat['Bat'/4725, l='MpServer', x=114,71, y=32,53, z=222,87], EntityItem['item.item.flint'/4732, l='MpServer', x=98,76, y=50,79, z=205,50], EntityPlayerSP['ddrmax'/4728, l='MpServer', x=106,20, y=65,00, z=209,51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 802906968 bytes (765 MB) / 2287468544 bytes (2181 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2107 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2107.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.2.2107} [Minecraft Forge] (forge-1.10.2-12.18.2.2107.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	immersiveengineering{0.10-47} [Immersive Engineering] (ImmersiveEngineering-0.10-47.jar) 
	UCHIJAAAAAAAAA	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCHIJAAAAAAAAA	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCHIJAAAAAAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAAAAAAA	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCHIJAAAAAAAAA	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCHIJAAAAAAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAAAAAAA	Baubles{1.3.BETA11} [Baubles] (Baubles-1.10.2-1.3.BETA11.jar) 
	UCHIJAAAAAAAAA	betterquesting{1.3.161} [Better Questing] (BetterQuesting-1.3.161.jar) 
	UCHIJAAAAAAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAAAAAAA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJAAAAAAAAA	Botania{r1.9-333} [Botania] (Botania r1.9-333.jar) 
	UCHIJAAAAAAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAAAAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAAAAAAA	CharsetLib{0.3.0-pre15} [â€½] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetAudio{0.3.0-pre15} [â™«] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetDecoration{0.3.0-pre15} [âš?] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAAAAAAA	chisel{MC1.9.4-0.0.6.53} [Chisel] (Chisel-MC1.9.4-0.0.6.53.jar) 
	UCHIJAAAAAAAAA	chiselsandbits{12.6} [Chisels & Bits] (chiselsandbits-12.6.jar) 
	UCHIJAAAAAAAAA	NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
	UCHIJAAAAAAAAA	craftingharmonics{1.9.4_1.10_1.10.2-1.5.7} [Crafting Harmonics] (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar) 
	UCHIJAAAAAAAAA	cyberware{beta-0.2.3} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.3.jar) 
	UCHIJAAAAAAAAA	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCHIJAAAAAAAAA	EnderStorage{2.1.3.72} [EnderStorage] (EnderStorage-1.10.2-2.1.3.72-universal.jar) 
	UCHIJAAAAAAAAA	exnihiloomnia{1.1.4} [Ex Nihilo Omnia] (exnihiloomnia-1.1.4.jar) 
	UCHIJAAAAAAAAA	excompressum{2.0.40} [Ex Compressum] (ExCompressum_1.10.2-2.0.40.jar) 
	UCHIJAAAAAAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.0.jar) 
	UCHIJAAAAAAAAA	flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.2.jar) 
	UCHIJAAAAAAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.1.jar) 
	UCHIJAAAAAAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.1.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAAAAAAA	Lockdown{${mod_version}} [Lockdown] (Lockdown-1.10.2-5.0.0-universal.jar) 
	UCHIJAAAAAAAAA	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
	UCHIJAAAAAAAAA	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
	UCHIJAAAAAAAAA	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
	UCHIJAAAAAAAAA	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJAAAAAAAAA	mxtune{0.3.1.0-dev.7} [mxTune] (mxtune-1.10.2-0.3.1.0-dev.7.jar) 
	UCHIJAAAAAAAAA	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 
	UCHIJAAAAAAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2g.jar) 
	UCHIJAAAAAAAAA	progressiveautomation{1.6.51} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51.jar) 
	UCHIJAAAAAAAAA	ProjectE{1.10.2-PE1.0.6B} [ProjectE] (ProjectE-1.10.2-PE1.0.6B.jar) 
	UCHIJAAAAAAAAA	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCHIJAAAAAAAAA	xreliquary{1.10.2-1.3.3.578} [Reliquary] (Reliquary-1.10.2-1.3.3.578.jar) 
	UCHIJAAAAAAAAA	rftools{5.57} [RFTools] (rftools-1.10-5.57.jar) 
	UCHIJAAAAAAAAA	rftoolscontrol{1.5.1} [RFTools Control] (rftoolsctrl-1.10-1.5.1.jar) 
	UCHIJAAAAAAAAA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJAAAAAAAAA	soulshardstow{1.10.2-2.6.4-44} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.4-44.jar) 
	UCHIJAAAAAAAAA	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHIJAAAAAAAAA	bq_standard{1.3.92} [Standard Expansion] (StandardExpansion-1.3.92.jar) 
	UCHIJAAAAAAAAA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJAAAAAAAAA	totemic{1.9.4-0.7.8.1} [Totemic] (Totemic-1.9.4-0.7.8.1.jar) 
	UCHIJAAAAAAAAA	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCHIJAAAAAAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAAAAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
CCCDeobfPlugin (unknown)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  
ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.53.jar)
  team.chisel.common.asm.ChiselTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.70' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	CodeChickenCore: ignoreInvalidMCVersion state: false
	Launched Version: forge-12.18.2.2107
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.5.0 NVIDIA 375.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Fanver_Modded_Universal.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by ddrmax** [comment]
sorry after reparing the issue (removing restone dust) the problem was from the extra utilities crafter
