### ISSUE TITLE
Persistant server crash with elevator - empty string not allowed

### ISSUE THREAD

**Issue by melekaiah** [McJty/RFTools#853]
basically i placed elevator block behind a creative energy thingy from rftools. rightclicked the elevator block. (it had no blocks in front of it.) and the client insta crashed, and then the server too, server rebooted. but as soon as i logged in crashed again with the following error. 

hope this helps. 

`[22:32:15] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: Melekaiah
[22:32:15] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[22:32:15] [Server thread/ERROR] [FML/]: A TileEntity type mcjty.rftools.blocks.elevator.ElevatorTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ee.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:128) ~[dr.class:?]
	at mcjty.rftools.blocks.elevator.ElevatorTileEntity.writeRestorableToNBT(ElevatorTileEntity.java:782) ~[ElevatorTileEntity.class:?]
	at mcjty.lib.entity.GenericTileEntity.func_189515_b(GenericTileEntity.java:237) ~[GenericTileEntity.class:?]
	at mcjty.lib.entity.GenericEnergyStorageTileEntity.func_189515_b(GenericEnergyStorageTileEntity.java:50) ~[GenericEnergyStorageTileEntity.class:?]
	at mcjty.rftools.blocks.elevator.ElevatorTileEntity.func_189515_b(ElevatorTileEntity.java:724) ~[ElevatorTileEntity.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1012) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:393) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by 3Pixel** [comment]
looks like this is the same.
https://github.com/McJty/RFTools/issues/852

**Comment by McJty** [comment]
Fixed next release

**Comment by xenoflot** [comment]
Confirmed working in v61 \o/
