### ISSUE TITLE
Spawner causing NPE crash

### ISSUE THREAD

**Issue by eractnod** [McJty/RFTools#953]
MC Version 1.11.0 on forge 2188 with RFTools 1.1x-5.72
Tried to make a wither skeleton spawner. Added RF to the spawner and 3 matter beamers.  Placed bones, netherrack, and wheat.  Flicked the first lever and the system crashed.  Also is attached a screen shot of the spawner gui.  Did not show items needed.

PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mcjty.lib.tools.ItemStackTools.isEmpty(ItemStackTools.java:71)
	at mcjty.rftools.blocks.spawner.SpawnerConfiguration$MobSpawnAmount.match(SpawnerConfiguration.java:386)
	at mcjty.rftools.blocks.spawner.SpawnerTileEntity.addMatter(SpawnerTileEntity.java:142)
	at mcjty.rftools.blocks.spawner.MatterBeamerTileEntity.checkStateServer(MatterBeamerTileEntity.java:106)
	at mcjty.rftools.blocks.spawner.MatterBeamerTileEntity.func_73660_a(MatterBeamerTileEntity.java:54)
	at net.minecraft.world.World.func_72939_s(World.java:1827)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

![2016-12-25_17 48 57](https://cloud.githubusercontent.com/assets/5204558/21473189/3535b826-cacc-11e6-85b3-1a1509659f4f.png)

**Comment by McJty** [comment]
Fixed next release (both the crash and the ability to spawn). You might have to renegenerate the config file
