### ISSUE TITLE
Crash on opening Extra Utilities Filing Cabinet with Dimlets inside.

### ISSUE THREAD

**Issue by Alexei-B** [McJty/RFTools#97]
This is reproducible for me.

Using FTB Infinity 1.2.0

Crash Log:
http://pastebin.com/ewajdV5z

Let me know if you need any other details or if I should report this to Extra Utilities instead of RFTools.

I believe this is a problem with RFTools because from the crash log stack trace:
```
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:502)
    at com.rwtema.extrautils.gui.GuiFilingCabinet$ItemSorter.compare(GuiFilingCabinet.java:224)
    at com.rwtema.extrautils.gui.GuiFilingCabinet$ItemSorter.compare(GuiFilingCabinet.java:208)
    at java.util.TimSort.binarySort(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.Arrays.sort(Unknown Source)
    at java.util.Collections.sort(Unknown Source)
    at com.rwtema.extrautils.gui.GuiFilingCabinet.sortItems(GuiFilingCabinet.java:53)
    at com.rwtema.extrautils.gui.GuiFilingCabinet.func_73863_a(GuiFilingCabinet.java:200)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
```

As you can see the crash happens from an uncaught NullPointerException when EU tries to compare one stack to the other, I _think_ the responsibility for making compare work should be part of the item stack not EU, but I don't know that so I could totally be wrong to report this here.

**Comment by McJty** [comment]
It would be nice if you could also report this to EU. If only to be able to figure out what exactly EU is doing there so that I can know why this is failing. Because I see no rftools code in the stacktrace it is a bit hard to know where the null comes from

**Comment by McJty** [comment]
It is likely this is fixed with the somewhat more robust item handling code in rftools. If not reopen.
