### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#98]
Greetings, 

I have FTB Infinity Installed, and it is currently at 1.2.0. 

I manually updated to RF Tools 2.6 (due to some issues which where fixed). 

However now, when i create a new dimension, let it power up, when i click on the dialing device - randomly it will crash me to desktop, it'll keep doing this even though restarts. 

To fix the issues, all i have to do is break the block (i am using a pick axe), and replace it - and it starts working fine. 

------------------------------
[00:18:07] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Don't do that.

Time: 3/15/15 12:18 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-----------------------------------------------------
I can't  see how to attact a text file, If you need anymore information feel free to contact me - i'll try my best to provide what you need.

**Comment by McJty** [comment]
Closing because this is most likely outdated and no longer an issue

**Comment by zack11111111** [comment]
Its still here in 1.7.10 for me.

**Comment by chemban** [comment]
Similar Issue, I can go between dimensions just fine, but when I try to place a block in the RF dimension I get a null point error.  I can restart the game and build to my hearts desire.  but if i leave the dimension and go back it will crash again. 

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 4/11/16 3:31 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@7afb954c
Stacktrace:
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by McJty** [comment]
I need to see a full log

**Comment by chemban** [comment]
[crash-2016-04-11_15.31.53-server.txt](https://github.com/McJty/RFTools/files/215689/crash-2016-04-11_15.31.53-server.txt

**Comment by chemban** [comment]
OK I figured it out, because I don't drop below 40 fps I don't experience any visual lag, but it seems that there is something going on under the hood because if I move items around in the inventory they appear to duplicate.  If I wait till the icon changes back everything works fine.  Is this something you can fix, or is it just some kind of lag related to the way the RF tools dimensions load.
